### ISSUE TITLE
Syntax error in graph when codeblock is wrapped in html <details> tag

### ISSUE THREAD

**Issue by disambiguationuk** [mjbvz/vscode-markdown-mermaid#102]
I'm using a Github Action which leaves the codeblock wrapped in an html tag like this:

```
- <details>
-   <summary>Mermaid markup</summary>
- 
- ```mermaid
-     erDiagram
- 
- ```
- </details>
```

On preview with this setup it both renders the diagram and an overlay saying "Syntax error in graph mermaid version 8.9.0

![image](https://user-images.githubusercontent.com/11738048/113118375-509fac00-9207-11eb-966d-5f494bbb9dd6.png)

**Comment by mjbvz** [comment]
Seems to work fine for me:

<img width="903" alt="Screenshot 2022-12-05 at 6 46 19 PM" src="https://user-images.githubusercontent.com/12821956/205796671-1228d2e0-63d5-465b-bd39-9afcabe701ca.png">

Let me know if there's a case that still doesn't work
