### ISSUE TITLE
Big gap before / after diagram when scaling to fit editor's width

### ISSUE THREAD

**Issue by bcardiff** [mjbvz/vscode-markdown-mermaid#109]
I noticed the preview has a fixed height for diagrams

![3JgrvKPYyq](https://user-images.githubusercontent.com/459923/122095732-1eecb900-cde4-11eb-80f9-52823184f5af.gif)

that seems good for small / medium diagrams, but when the content is wide the gap starts to be a problem (unless you have a ultra wide monitor 😅 )

![wcwaG5q5fD](https://user-images.githubusercontent.com/459923/122095741-23b16d00-cde4-11eb-85c1-7d60d2aac65f.gif)

The scaling to fit editor's width is a nice feature. Maybe keeping a fixed height was on purpose, i don't know. Would it make sense to remove that gap and allow diagram's height to change as needed?

---

Thanks for this plugin! 💙

**Comment by bobatsar** [comment]
I have the same problem, seems to be already in mermaid not in this plugin.
https://github.com/mermaid-js/mermaid/issues/1984

**Comment by bcardiff** [comment]
Thanks! Closing then since is in mermaidjs and not in this repo.
