### ISSUE TITLE
Support for pandoc/etc. fenced_code_attributes

### ISSUE THREAD

**Issue by larsw** [mjbvz/vscode-markdown-mermaid#11]
Hi,

 Have you considered supporting fenced_code_attributes [1], so it is possible to add extra HTML classes and parameters to things like pandoc (I'm currently working on a new pandoc-mermaid-filter that will use Inkscape to render mermaid-svg to PDF or EMF for inclusion in PDFs and DocX. It would be useful to be able to supply parameters, and at the same time use your extension to preview the files in VS Code.

[1]  https://pandoc.org/MANUAL.html#fenced-code-attributes

**Comment by mjbvz** [comment]
Probably beyond the scope of this extension but I think a [vscode markdown it extension](https://code.visualstudio.com/docs/extensionAPI/api-markdown#_adding-support-for-new-syntax-with-markdownit-plugins) could contribute this.

Let me know if you are interested in creating this or run into issues with the markdown extension API

**Comment by mjbvz** [comment]
Supporting `{.mermaid`  as a language identifier was addressed by #12. We still don't forward along the extra attributes however. @larsw is that still something you'd like to see?

**Comment by larsw** [comment]
@mjbvz Well, it would be nice if it was possible to pass down the actual parameters to the extension, but that might be an API change for the overlying extension point as far as I can see. It should be possible to add an additional argument:

```javascript
md.options.highlight = (code, lang, parameters) => { ... }
```

That can pass down optional parameters.
For the vscode-markdown-mermaid extension, parameters like `width` and `height` could be passed on to the `div/code` tags used to hold the mermaid definition.

**Comment by mjbvz** [comment]
Closing since there have not been any upvotes on this
