### ISSUE TITLE
vscode can not render the mermaid view

### ISSUE THREAD

**Issue by heartacker** [mjbvz/vscode-markdown-mermaid#120]
![image](https://user-images.githubusercontent.com/1876302/148000918-618f5d0a-f528-49ba-ac87-27cde8a4c535.png)

but I can see it in another extension ( Markdown Preview Enhanced)
![image](https://user-images.githubusercontent.com/1876302/148000970-92499e20-d3f9-4666-95b8-3ae0f68a232c.png)

名称: Markdown Preview Enhanced
ID: shd101wyy.markdown-preview-enhanced
说明: Markdown Preview Enhanced ported to vscode
版本: 0.6.1
发布者: Yiyi Wang
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced

**Comment by mjbvz** [comment]
Please always share the text of the code along with screenshots

**Comment by heartacker** [comment]
sorry

and the code
``````
```mermaid
flowchart TD
subgraph PowerOnReset
   subgraph RESET TRAPPING
        wait((48CYCYLE))
        TRAP_RDY(TRAPPING 准备)-->RST(释放)-->DONETRAPPING(TRAP 完毕)
   end
   PNO((POWER ON)) ==>|复位一直拉低|TRAP_RDY
end

   subgraph CALIB EN
        wcaliben(写入校准使能)-.->RRST(复位)
   end
   DONETRAPPING -.-> wcaliben
   DONETRAPPING==>SW_CLK

   subgraph CLOCK_SWITCH
        SW_CLK(写寄存器切换时钟)
   end

   RRST==>SW_CLK
   SW_CLK(写入校准寄存器) x--x TEST

   MAIN:
    subgraph PowerOnReset_
    A((power on)) ==> T(RESET TRAPPING)
    end
    T -.-> C(CALIB EN)
    C -..->T
    C==>S(CLOCK_SWITCH) x--x TS(TEST)
    T---->S
```
``````

**Comment by heartacker** [comment]
enable this will cause the issue
https://marketplace.visualstudio.com/items?itemName=mathpix.vscode-mathpix-markdown

**Comment by mjbvz** [comment]
So the issue only happens when that extension is installed? If so, please file an issue against that extension

**Comment by SibongaS** [comment]
@heartacker hello, I know its been 3 years since you closed this, but I have the exact same issue. Mermaid view will not render.
Two, I cannot create files with a custom file name, I have to save on desktop to be able to rename files.
Please help, I’m kinda new to this.

**Comment by mjbvz** [comment]
@SibongaS First try disabling all extensions except this one and then restarting VS Code. If you still see the issue after that, please open a new issue with any relevant info to reproduce the problem
