### ISSUE TITLE
No syntax highlighting for `actor` keyword in syntaxDiagram

### ISSUE THREAD

**Issue by gtd-oneome** [mjbvz/vscode-markdown-mermaid#123]
The syntax highlighting does not highlight the `actor` keyword.

![image](https://user-images.githubusercontent.com/95307735/153289094-da04d9d2-3e0b-4abf-a0a6-b815650c9b9b.png)

**Comment by mjbvz** [comment]
This extension does not actually provide syntax highlighting, just the rendering. Please file an issue against whatever extension is providing the highlighting
