### ISSUE TITLE
Class Diagram: Arrows wrong 

### ISSUE THREAD

**Issue by norbertfrei** [mjbvz/vscode-markdown-mermaid#127]
In UML the inheritance and the implementation of interfaces is drawn with a non filled triangle.
At the moment the triangles are filled (black), which is wrong.

Inheritance is drawn with a isosceles triangle (at the backside it should be broader)

**Comment by mjbvz** [comment]
Closing as more information needed. From the description, this sounds like an upstream issue with mermaid itself
