### ISSUE TITLE
Graph lines getting cut off.

### ISSUE THREAD

**Issue by fuzzybear3** [mjbvz/vscode-markdown-mermaid#139]
I know there are some zoom issues, but I made sure to reset my vscode zoom level.

![image](https://user-images.githubusercontent.com/18566094/180393078-fba91618-1afa-4aca-86b8-5dac98950df4.png)

**Comment by mjbvz** [comment]
Seems to work fine for me in latest release with various zoom levels:

/Users/matb/Desktop/Screenshot 2022-12-05 at 6.49.47 PM.png
