### ISSUE TITLE
latex + mermaid

### ISSUE THREAD

**Issue by thedranovski** [mjbvz/vscode-markdown-mermaid#14]
hi, any suggestions on rendering latex within a mermaid block? or parsing .md containing mermaid using pandoc, to produce eg. .pdf?

**Comment by mjbvz** [comment]
Please try asking this on StackOverflow

**Comment by hamad12a** [comment]
There should be a way to use this extension along with [this branch](https://github.com/NicolasNewman/mermaid/tree/feature/2776_katex_math)

**Comment by bieye250** [comment]
> There should be a way that this extension be compatible along with [this branch](https://github.com/NicolasNewman/mermaid/tree/feature/2776_katex_math)

Can you help me about how to use Latex in mermaid with the Vscode extension?

**Comment by hamad12a** [comment]
> > There should be a way that this extension be compatible along with [this branch](https://github.com/NicolasNewman/mermaid/tree/feature/2776_katex_math)
> 
> Can you help me about how to use Latex in mermaid with the Vscode extension?

[Does] (https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) help?
