### ISSUE TITLE
Note in extension description whether it performs purely client-side rendering

### ISSUE THREAD

**Issue by mdlemay** [mjbvz/vscode-markdown-mermaid#143]
This extension apparently performs client-side rendering without uploading diagram data to a remote server (here I'm considering a machine accessed via the VSCode "Remote - ..." extensions as equivalent to a local machine). If that's correct, it would be useful to note it in the extension description.

**Comment by mjbvz** [comment]
Why do you think it would be helpful?

**Comment by mdlemay** [comment]
Some users prefer to have diagram data processed locally and not sent to a remote server, e.g., if the diagram depicts an algorithm that is confidential to a company.

**Comment by mjbvz** [comment]
I agree we should note if this extension did send data to some third party server but I don't think it's useful to note things that the extension doesn't do
