### ISSUE TITLE
Vertical Padding/Margin on long sequence diagrams is incorrect/huge

### ISSUE THREAD

**Issue by yev-yev-yev** [mjbvz/vscode-markdown-mermaid#155]
**How To Reproduce**

1. Make a long sequence diagram (~15+ steps)
2. Keep adding steps
3. Observe that padding/margin above and below the diagram increase with each new step

Additional Info: I used `loop` and `par` in this diagram, and it has 6 participants

**EDIT**
This only happens with the GitHub Styling extension enabled - https://github.com/mjbvz/vscode-github-markdown-preview-style

**Comment by mjbvz** [comment]
Please share the text of a diagram that causes this issue

**Comment by yev-yev-yev** [comment]
It seems to be fixed with the latest updates
