### ISSUE TITLE
Subgraph links don't display with Mermaid 9.16. Upgrade to 9.22

### ISSUE THREAD

**Issue by stephenandary** [mjbvz/vscode-markdown-mermaid#156]
Is it possible to update the version from 9.16 -> 9.22? Trying to use subgraph connections, and they don't work with 9.16. I have seen posts that state the beta version supports subgraph connections, but Mermaid's official docs show subgraph connections so I believe 9.22 will suffice.

**Comment by piranna** [comment]
I just came to ask for the same :-) Can we get an update of the `mermaid` dependency? Is there any way to use a custom patched extension with it, the same way you can use a git dependency on npm?

**Comment by stephenandary** [comment]
GitHub itself will also need to upgrade, learned that after this.

**Comment by piranna** [comment]
> GitHub itself will also need to upgrade, learned that after this.

Yes, in fact Github version is older, but at least this can help to debug it easier until they fix it.

**Comment by stephenandary** [comment]
Agreed, I have been copy and pasting into mermaid live which is a bit tedious lol

**Comment by piranna** [comment]
Maybe better error messages would be nice, but that's an issue of mermaid itself.

**Comment by stephenandary** [comment]
> Fixed by 1.15.3. In the future, please consider submitting a PR for mermaid version bumps as it's pretty straightforward  

Good to know, will do.

**Comment by piranna** [comment]
> In the future, please consider submitting a PR for mermaid version bumps as it's pretty straightforward

Agree on that.
