### ISSUE TITLE
integrate mermaind diagrams in jupiter notebooks (Visual Studio Code)

### ISSUE THREAD

**Issue by ITCTOM** [mjbvz/vscode-markdown-mermaid#158]
Is it possible to integrate mermaind Diagrams als "Markdown Cells" to jupiter Notebooks using .net Interactive?

**Comment by ITCTOM** [comment]
now it´s working using "Polyglot Notebooks" Plugin.

**Comment by mjbvz** [comment]
Duplicate of #137
