### ISSUE TITLE
Add support for line breaks (i.e., <br>) within strings of text

### ISSUE THREAD

**Issue by michael-booker** [mjbvz/vscode-markdown-mermaid#163]
Would it be possible for the preview to respect &lt;br&gt; and &lt;br/&gt; in strings of text within a node or line.
Following examples taken from: [Other Mermaid Examples](https://mermaid-js.github.io/mermaid/syntax/examples.html)

    subgraph A
        od>Odd shape]-- Two line<br/>edge comment --> ro
        di{Diamond with <br/> line break} -.-> ro(Rounded<br>square<br>shape)
        di==>ro2(Rounded square shape)
    end

    %% Notice that no text in shape are added here instead that is appended further down
    e --> od3>Really long text with linebreak<br>in an Odd shape]

    %% Comments after double percent signs
    e((Inner / circle<br>and some odd <br>special characters)) --> f(,.?!+-*ز)

Thank you!

**Comment by mjbvz** [comment]
This already seems to work:

<img width="1629" alt="Screenshot 2022-12-15 at 12 04 04 PM" src="https://user-images.githubusercontent.com/12821956/207956182-2c3e75be-d8a8-4b18-9af9-89a682fc3c64.png">

The note on the right use `<br>`

If you're still not seeing this working, please share a complete example that demonstrates the issue . The one original included does not work in its current state

**Comment by michael-booker** [comment]
I agree that it appears to work on the Note, but not in Nodes or in Line text. Please copy and paste the following code into a markdown file in Visual Studio Code and preview using "Markdown Preview Mermaid Support v1.16.0".

<pre class="mermaid">
%%{ init: { 'flowchart': { 'curve': 'bump' } } }%%
flowchart TD
   IPSC -->|Hey there<br>This is some<br>text that I want<br>on different lines| TBH -->|As you can see<br>it is not wrapped<br>in the preview| I:D
   RC -->|This is what I<br>am requesting| I:D

   IPSC[Hey there!<br>This line should be wrapped]
   TBH[And this one<br>too]
   I:D[Title<br>Descriptive text]
   RC[Single line]
      
   classDef paleBlue fill:lightblue,color:black;
   class IPSC paleBlue;
   classDef paleYellow fill:Wheat,color:black;
   class TBH,I:D paleYellow;
   classDef paleGreen fill:lightgreen,color:black;
   class RC paleGreen;
</pre>

**Comment by michael-booker** [comment]
![MarkdownPreviewLinebreakIssue](https://user-images.githubusercontent.com/29759085/207959723-1d6895e6-1a84-41b7-9d5c-4d5dbe9fd5e3.png)

**Comment by michael-booker** [comment]
![MarkdownPreviewLinebreakIssue](https://user-images.githubusercontent.com/29759085/207960053-2fa270d6-98d7-48fa-8afe-9784692908b0.png)

**Comment by mjbvz** [comment]
Does that example work on https://mermaid.live? I get a error on line 3

**Comment by michael-booker** [comment]
Yep, it sure does.
![MarkdownPreviewLinebreakIssue2](https://user-images.githubusercontent.com/29759085/207967033-5ecb9344-0f91-4b29-80d0-19b3e998c899.png)

**Comment by michael-booker** [comment]
And Typora as well.
![MarkdownPreviewLinebreakIssue3](https://user-images.githubusercontent.com/29759085/207967328-a9ef8d3b-d35f-417e-8bbc-82e607055957.png)

**Comment by mjbvz** [comment]
Please you share that text in its original state. Your example code is different than what the screenshots show (seems like there are literal new lines in it): https://github.com/mjbvz/vscode-markdown-mermaid/issues/163#issuecomment-1353665817

**Comment by michael-booker** [comment]
Following is the exact code that is used in Visual Studio Code.  The other code snippets are exactly the same except mermaid.live does not like `<pre class="mermaid">...<pre>` and Typora prefers fenced code `'''mermaid...'''`.  That is literally the only difference.  Besides, it's simple enough to reproduce this by putting an HTML break `<br>` in any non-Note string of text.  It is possible that this is an issue with flowcharts alone?

# Request

<pre class="mermaid">
%%{ init: { 'flowchart': { 'curve': 'bump' } } }%%
flowchart TD
   IPSC -->|Hey there<br>This is some<br>text that I want<br>on different lines| TBH -->|As you can see<br>it is not wrapped<br>in the preview| I:D
   RC -->|This is what I<br>am requesting| I:D

   IPSC[Hey there!<br>This line should be wrapped]
   TBH[And this one<br>too]
   I:D[Title<br>Descriptive text]
   RC[Single line]
      
   classDef paleBlue fill:lightblue,color:black;
   class IPSC paleBlue;
   classDef paleYellow fill:Wheat,color:black;
   class TBH,I:D paleYellow;
   classDef paleGreen fill:lightgreen,color:black;
   class RC paleGreen;
</pre>

**Comment by michael-booker** [comment]
Word wrap on the editors might make it appear differently as well, but it is all the same example.

**Comment by mjbvz** [comment]
Ok, I figured out what is going on and fixed your code example. In the future, just use a markdown fenced code block instead of a `<pre>` (which causes the `<br>` to be rendered instead as treated as text)

**Comment by mjbvz** [comment]
The example seems to work for me though?

<img width="1215" alt="Screenshot 2022-12-15 at 1 29 04 PM" src="https://user-images.githubusercontent.com/12821956/207970893-2e6fe3af-7445-4b62-b0bb-1d8d1f1b883d.png">

**Comment by michael-booker** [comment]
Well I'll be darned.  That worked!  Yes, fencing the code works while using <pre> does not.  That you very much!  My apologies for the run around.
