### ISSUE TITLE
Update Mermaid to 9.3.0

### ISSUE THREAD

**Issue by znorris** [mjbvz/vscode-markdown-mermaid#164]
Upgrade to Mermaid 9.3.0 to support new features <https://github.com/mermaid-js/mermaid/releases/tag/v9.3.0>.

Thanks for making this extension, very useful!

**Comment by mjbvz** [comment]
Want to submit a pr for this? It should be pretty straightforward

**Comment by apeacock1991** [comment]
I've raised a PR here: https://github.com/mjbvz/vscode-markdown-mermaid/pull/165. Strangely `npm install` doesn't work for me on master (it complaints a lot about deps, particularly mermaid-markdown/webpack etc.) but based on a prior PR these are the only changes required.

**Comment by znorris** [comment]
@apeacock1991 Thank you for doing this! I had the same problem with getting master to build so that's why I didn't go ahead and make a PR. I appreciate this extension @mjbvz and the awesome people that keep it up to date @apeacock1991.
