### ISSUE TITLE
Images not being rendered since 1.15.3

### ISSUE THREAD

**Issue by thattanmay** [mjbvz/vscode-markdown-mermaid#166]
<img width="964" alt="img" src="https://user-images.githubusercontent.com/25507525/208486986-87a76850-69d8-4935-9e72-889ad838b7ab.png">

Since the Dec releases, images are not being rendered via the HTML syntax, reverting back to 1.15.2 works fine.

**Comment by mjbvz** [comment]
Please share steps to reproduce this (including the chart code as text)

**Comment by thattanmay** [comment]
Apologies for late reply, please find the code below to reproduce:
`
```mermaid
graph TD



IRON_PLATE(( <img src='https://wiki.factorio.com/images/thumb/Iron_plate.png/32px-Iron_plate.png' /> ))
IRON_ORE(( <img src='https://wiki.factorio.com/images/thumb/Iron_ore.png/32px-Iron_ore.png' /> ))

IRON_ORE --> IRON_PLATE

```
`

version: 1.15.2
<img width="809" alt="1 15 2" src="https://user-images.githubusercontent.com/25507525/209199000-a57baa76-32f5-432c-a756-a98d778b2b31.png">

version: 1.17.3(latest)
<img width="791" alt="1 17 3(latest)" src="https://user-images.githubusercontent.com/25507525/209199110-ed61b632-99b9-4c03-95a2-b31929cf9962.png">

in the earlier version I'm able to render images as nodes from URL, in the newer version this functionality is broken
