### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'rank') when pointing a node to a subgraph

### ISSUE THREAD

**Issue by hyperrecursive** [mjbvz/vscode-markdown-mermaid#168]
Here is the example code:

~~~
```mermaid
graph LR
    subgraph sg0
        node0 --> sg1
        node0 --> node2
        subgraph sg1
            node3
        end
        subgraph sg2
        end
    end
```
~~~

In VS Code (and GitHub as well), the following error is printed:

```
TypeError: Cannot set properties of undefined (setting 'rank')
```

It should be possible according to [#644](https://github.com/mermaid-js/mermaid/issues/644). This is how it is rendered in the [live editor](https://mermaid.live/):

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/12224339/209240339-ba73ab0d-f669-41ee-b603-9187d8ded28e.png">

**Comment by mjbvz** [comment]
Renders fine for in the latest extension version:

![Screenshot 2023-01-23 at 5 04 10 PM](https://user-images.githubusercontent.com/12821956/214191963-5c8d9548-ec1f-4c49-8bea-7174229ef3ee.png)

**Comment by hyperrecursive** [comment]
I've just tested it again and found out that the [Markdown Preview Enchanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) steals the rendering of Mermaid diagrams if both extensions are enabled.
