### ISSUE TITLE
Extension not working on some systems

### ISSUE THREAD

**Issue by brianary** [mjbvz/vscode-markdown-mermaid#170]
I'm not really sure how to diagnose this, but the extension isn't doing anything on one (maybe more) of my systems:

![image](https://user-images.githubusercontent.com/8332839/209910352-21995610-df0c-4aa8-ab90-ea935026e27f.png)

**Comment by rdkleine** [comment]
Same here. Not sure exactly when this problem started but within the last two weeks.

**Comment by mjbvz** [comment]
Please share:

1. info about your system
1. which VS Code version you are using
2. An example markdown file

**Comment by brianary** [comment]
I should be able to add better detail in about seven hours.

**Comment by takondra** [comment]
Same here. v1.16 works, but the v1.17.3 doesn't render properly.
This is rendered into a single space-separated string `graph TD; A-->B; A-->C; B-->D; C-->D;` instead of a diagram image.
````
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````

VSCode version:
```
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No
```

**Comment by brianary** [comment]
The extension is working on my work system. More systems to follow.

VSCode:

```text
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z (2 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

**Comment by brianary** [comment]
Not working on my personal desktop.

    Test
    ====
    
    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```

![image](https://user-images.githubusercontent.com/8332839/210904766-dac8bbac-3112-4f87-a7fb-a77a3ba83f1d.png)

VSCode:

```text
Version: 1.75.0-insider (system setup)
Commit: f076d553210e9ea65e7bccbfa2f7a786c10fcab2
Date: 2022-12-09T09:11:59.691Z (3 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
```

**Comment by brianary** [comment]
The extension started working again on my personal laptop.

VSCode:

```text
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z (2 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by mjbvz** [comment]
Closing as not actionable without any more info or steps to reproduce the problem

If you're still seeing this, please try narrowing down what specifically causes this and if there are any error messages that might explain the problem
