### ISSUE TITLE
Gannt issue with tickInterval

### ISSUE THREAD

**Issue by tropicalgarlicbread** [mjbvz/vscode-markdown-mermaid#173]
If I try to use tickInterval, the graph shows a syntax error for mermaid version 8.8.0 which is odd. For example the below renders fine on [Mermaid Live](https://mermaid.live).

```
gantt
  title xxx
  dateFormat YYYY-MM-DD
  axisFormat %Y-%b
  tickInterval 3 months
  T1 :milestone, 2023-05-01, 1d
  T2 :milestone, 2028-01-01, 1d
```

**Comment by mjbvz** [comment]
Should work in latest release now that we're using mermaid 9.4
