### ISSUE TITLE
Fails to render with mermaid titles

### ISSUE THREAD

**Issue by luispabon** [mjbvz/vscode-markdown-mermaid#18]
![image](https://user-images.githubusercontent.com/6388823/40050032-3b5bcf06-582e-11e8-8a68-8685edd1cee6.png)

**Comment by luispabon** [comment]
```mermaid
sequenceDiagram
    title Request Response lifecycle
    Client->>Request Validation: JSONAPI request
    Request Validation->>Request deserialiser: JSONAPI
```
```mermaid
sequenceDiagram
    Client->>Request Validation: JSONAPI request
    Request Validation->>Request deserialiser: JSONAPI
```

**Comment by mjbvz** [comment]
Is the first block valid? I see this error using the [mermaid editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgdGl0bGUgUmVxdWVzdCBSZXNwb25zZSBsaWZlY3ljbGVcbiAgICBDbGllbnQtPj5SZXF1ZXN0IFZhbGlkYXRpb246IEpTT05BUEkgcmVxdWVzdFxuICAgIFJlcXVlc3QgVmFsaWRhdGlvbi0-PlJlcXVlc3QgZGVzZXJpYWxpc2VyOiBKU09OQVBJIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgouLi5jZURpYWdyYW0gICAgdGl0bGUgUmVxdWVzdCBSZXNwb25zZSBsaWYuLi4KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLV4KRXhwZWN0aW5nICdUWFQnLCBnb3QgJ0FDVE9SJw):

```
Parse error on line 2:
...ceDiagram    title Request Response lif...
----------------------^
Expecting 'TXT', got 'ACTOR'
```

**Comment by luispabon** [comment]
Mmm perhaps it isn't valid after all. I can't see anything either way on mermaid documentation, but title is a thing in some of the diagrams. Closing then :+1:
