### ISSUE TITLE
The Invisible link is not recognized

### ISSUE THREAD

**Issue by emersonmello** [mjbvz/vscode-markdown-mermaid#186]
Hi!

First of all, this VSCode extension is fantastic. Congratulation!

I'm using v1.17.5 (March 06, 2023). The invisible link is still not working.

PS: The original issue #149 was closed, so I'm opening a new one.

**Comment by NoMoosey** [comment]
I'm also encountering the same :point_up:

**Comment by zozovo** [comment]
☝️

**Comment by emersonmello** [comment]
The v[1.18.0](https://github.com/mjbvz/vscode-markdown-mermaid/releases/tag/1.18.0) fixed it.
