### ISSUE TITLE
Loading chunk 366 failed.

### ISSUE THREAD

**Issue by mjbvz** [mjbvz/vscode-markdown-mermaid#187]
It works if I turn off my security settings.

_Originally posted by @isaacsanders in https://github.com/mjbvz/vscode-markdown-mermaid/issues/153#issuecomment-1458916214_

**Comment by mjbvz** [comment]
@isaacsanders What security settings?

**Comment by isaacsanders** [comment]
In the dialog in VS Code titled: “Select security settings for Markdown previews in this workspace”
