### ISSUE TITLE
Detect mermaid code block in more formats

### ISSUE THREAD

**Issue by jakepearson** [mjbvz/vscode-markdown-mermaid#19]
Is it possible to find mermaid code blocks in more places in a markdown files? Here are some examples:

HTML
```
<div class="mermaid">
sequenceDiagram
  A-->B: Works!
</div>
```

Hugo
```
{{<mermaid attr="val">}}
sequenceDiagram
  A-->B: Works!
{{</mermaid>}}
```

Even more here: https://github.com/vstirbu/vscode-mermaid-preview

**Comment by mjbvz** [comment]
The first example should already work. If you or someone wants to add a PR to support the second too I'll merge it in

**Comment by mjbvz** [comment]
Closing since there have not been any upvotes on this since it was opened
