### ISSUE TITLE
class labels does not work

### ISSUE THREAD

**Issue by geniys** [mjbvz/vscode-markdown-mermaid#198]
The class labels are not rendered.
It described in https://mermaid.js.org/syntax/classDiagram.html#class-labels.

plugin version is v1.18.1

Thanks

**Comment by mjbvz** [comment]
Seems to be rendering for me now in version 1.21 of this extension:


![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/886b1093-64e9-4db6-9e17-8fd788eda4df)


Rendering matches what I see on the mermaid website
