### ISSUE TITLE
timeline isn't supported

### ISSUE THREAD

**Issue by asklar** [mjbvz/vscode-markdown-mermaid#199]
mermaid supports a timeline chart type, but i can't get it to work in vscode
example: https://mermaid.js.org/syntax/timeline.html#an-example-of-a-timeline

**Comment by mjbvz** [comment]
Works fine for me:

![Screenshot 2023-05-17 at 3 37 50 PM](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/4495b7d8-4a0a-462e-a68f-3430edfd9218)

Please share example markdown where it doesn't work

**Comment by asklar** [comment]
thanks for replying @mjbvz 
if I use the right click on the markdown file's pane contents and select Markdown Preview Enhanced: Open Preview to the Side, it doesn't work.
But if I do ctrl+shift+P and select "Markdown Preview: Open Preview to the Side", then it works
So maybe I need to file a bug here instead? https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues

<img width="832" alt="image" src="https://github.com/mjbvz/vscode-markdown-mermaid/assets/22989529/73511a66-8335-40d9-8040-6b3545167d96">

**Comment by asklar** [comment]
FWIW the reason for me to use the Markdown Preview Enhanced is to be able to export the rendered markdown / diagrams. I couldn't find a way to do that, while MPE can save to PDF, HTML, etc.

**Comment by mjbvz** [comment]
Yes this extension only supports VS Code's built-in markdown preview. Please file an issue against Markdown Preview Enhanced
