### ISSUE TITLE
This extension doesn't work

### ISSUE THREAD

**Issue by HelloEdit** [mjbvz/vscode-markdown-mermaid#2]
Hello,

This is my README.md, like in the Changelog of VS code
```
```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
​```
```

And this is the preview:

![image](https://user-images.githubusercontent.com/25421857/29243729-a7cf656e-7fa6-11e7-9e01-33711d2679d3.png)

I'm using the latest VS Code

Thanks

**Comment by okwolf** [comment]
@HelloEdit are you installing using https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid?

**Comment by HelloEdit** [comment]
No, I tried from vsix file, like its explained in README

**Comment by Warr1611** [comment]
I installed from the Extensions tab. @HelloEdit 's text above gave me the same results, but the following works:
```mermaid
sequenceDiagram
    participant A
    participant B
    A -> J: Hello John, how are you?
    loop Healthcheck
        J->J: Fight against hypochondria
    end
    Note right of J: Rational thoughts <br/>prevail...
    J-->A: Great!
    J->B: How about you?
    B-->J: Jolly good!
```
![capture](https://user-images.githubusercontent.com/7979407/29287111-5bf307e2-8102-11e7-83f5-385d261c2fa3.PNG)

**Comment by HelloEdit** [comment]
Yep, I installed from the VS code market, and it work perfectly
