### ISSUE TITLE
Support for Mermaid 10.2+

### ISSUE THREAD

**Issue by chesterbr** [mjbvz/vscode-markdown-mermaid#202]
That one introduces `namespace` for class diagrams, which is quite useful.

It was [released](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.0) on 10.2.0 (the changelog says `package`, but the syntax is `namespace`, as [shown](https://mermaid.js.org/syntax/classDiagram.html#define-namespace) in the docs.

**Comment by ebtone** [comment]
> That one introduces `namespace` for class diagrams, which is quite useful.
> 
> It was [released](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.0) on 10.2.0 (the changelog says `package`, but the syntax is `namespace`, as [shown](https://mermaid.js.org/syntax/classDiagram.html#define-namespace) in the docs.

me too
