### ISSUE TITLE
Mermaid directives cause a parse error

### ISSUE THREAD

**Issue by matthias-colt** [mjbvz/vscode-markdown-mermaid#204]
If there are directives in the mermaid code, it is not rendered by this extension.
    
Example:

    ```mermaid
    flowchart LR
      %%{init: {'flowchart':{'useMaxWidth': false}}}%%
      A --> B
      A --> C
      B --> C
    ```

This causes an error:

    Parse error on line 2:
    flowchart LR  %%{init: {'flowchart
    --------------^
    Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'subgraph', 'end', 'acc_title', 'acc_descr', 'acc_descr_multiline_value', 'AMP', 'ALPHA', 'COLON', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'DEFAULT', 'NUM', 'COMMA', 'MINUS', 'BRKT', 'DOT', 'direction_tb', 'direction_bt', 'direction_rl', 'direction_lr', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'open_directive'

There is a PR #192  for support of directives, but this seems only for `settings.json` and not for the mermaid markup parser if I correctly understand.

**Comment by palto42** [comment]
Thanks, works for me as well now :)
