### ISSUE TITLE
There is no Icon in mindmap

### ISSUE THREAD

**Issue by Shapeno** [mjbvz/vscode-markdown-mermaid#209]
```mermaid
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectivness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```

the `::icon(fa fa-book)` is not rendered, but leaves a blank.

**Comment by Vince-1024** [comment]
Hi all,

No icon in flowchart too.

Thx

**Comment by mjbvz** [comment]
Please share the source markdown of that diagram

**Comment by Vince-perso** [comment]
Hi,
This is an example of what is no t working for me :
Code:
`
'''mermaid

  graph TD;
      A-->B[far:fa-window-maximize B];
      A-->C;
      B-->D;
      C-->D;

'''
`
Render:
```mermaid
  graph TD;
      A-->B[far:fa-window-maximize B];
      A-->C;
      B-->D;
      C-->D;
```

I hope this helps.
Thanks

**Comment by iainhallam** [comment]
In the live Mermaid editor at mermaid.js.org, you can use FontAwesome 5 icons with the `fa:fa-<icon-name>` syntax. This doesn't work in the VS Code extension, and like the original poster, I came here to see if it was something that could be enabled.

**Comment by mjbvz** [comment]
Please post the text of a diagram with the problem

**Comment by Vince1024** [comment]
Hi all,

If it helps, it's now working for me as I added this in my vscode config: 

![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/81962401/47128f0c-509d-47b2-93a9-238e2b39bf06)

**Comment by iainhallam** [comment]
> Please post the text of a diagram with the problem

```text
graph LR
net[fa:fa-network-wired Network]
```

In the online editor, this gives:

![Network with an icon](https://mermaid.ink/img/pako:eNolj80OgjAQhF-FzLkaBLHQs0f1oDeth41dlSgtqSX-EN7dirfZnd35Mj1OzjAULp7aa7Laams5HM6kzjSJ6un8bfKsPZtk85-O2kKgYd9QbeJjr22SaIQrN6yhojTkbxraDvGOuuB2b3uCCr5jga41FHhZU-Q1iJD7I25bslA9XlDVfJpnsijyai7LRSorgTdUPiunqVwUpcyKLC2rfBD4OBcDZgJs6uD8-l9jbDMG7kf_Rx2-86JI0g?type=png)

(Not quite sure why it's truncated...)

Sounds like from the workaround that @Vince1024 posted above, it would be enough to tell the extension to use FontAwesome's CSS.

**Comment by codekitchen** [comment]
The solution that @Vince1024 posted worked for me as well. Just so others don't have to copy from a screenshot, here's the vscode config JSON required:

```json
"markdown.styles": [
  "https://use.fontawesome.com/releases/v5.7.1/css/all.css"
]
```

Is it possible for this plugin to use this stylesheet by default?

**Comment by mjbvz** [comment]
Closing as it looks like adding the style sheet fixes this. This is documented in: https://github.com/mjbvz/vscode-markdown-mermaid?tab=readme-ov-file#using-custom-css-in-the-markdown-preview

If this keeps coming up we can consider always loading the FA stylesheet too
