### ISSUE TITLE
Mermaid not rendering in the preview

### ISSUE THREAD

**Issue by mathomp4** [mjbvz/vscode-markdown-mermaid#210]
I'm feeling kind of dumb here, but I can't seem to get this extension to work with even a simple case.

To wit, I have a test markdown file of:
````md
## Test

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````
but I see:

![Screenshot 2023-07-13 at 11 33 39 AM](https://github.com/mjbvz/vscode-markdown-mermaid/assets/2982494/1abd87fe-bda7-42e7-add2-f49771c29f92)

And the only "Mermaid" related extensions I have are this in v1.19.0 and a syntaxer, but disabling the latter doesn't seem to help.

I'm sure I've done something bad, but I'm also mainly a Fortran programmer that uses Vim so VS Code often confuses me. VS Code extensions, doubly so!

VSCode Info:
Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by mjbvz** [comment]
What if you disable all other extensions except this one?

**Comment by mathomp4** [comment]
@mjbvz I just tried that. Disabled everything and then reenabled this extension, but:

<img width="1679" alt="Screenshot 2023-07-14 at 6 22 21 PM" src="https://github.com/mjbvz/vscode-markdown-mermaid/assets/2982494/b1b2c32d-fa0b-4a0d-a9dc-50c2eb7a4a69">

Note that it does render on GitHub, see https://github.com/GEOS-ESM/GEOSgcm/wiki/Running-an-AMIP-Experiment#the-flow-of-the-gcm_runj-script

**Comment by mjbvz** [comment]
Unfortunately I can't reproduce this issue

Can you try viewing the developer tools to see if there are any errors. In the VS Code command palette, run `Developer: Toggle developer tools`. This should show the developer tools. Look in the console for potentially interesting error messages

**Comment by mathomp4** [comment]
@mjbvz Well, there were 35 messages when I started up:

[vscode-app-1689637103682.log](https://github.com/mjbvz/vscode-markdown-mermaid/files/12074442/vscode-app-1689637103682.log)

Your name is in some of them...but I also have like 10 of your extensions loaded 😄 

This all seems to be startup. If I clear the console and open the markdown preview, I get this log: 

[vscode-app-1689637161365.log](https://github.com/mjbvz/vscode-markdown-mermaid/files/12074447/vscode-app-1689637161365.log)

Nothing too exciting. 😦

**Comment by mjbvz** [comment]
Thanks. This is strange

What if you try the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? This will also have a fresh set of extensions and users settings

**Comment by mathomp4** [comment]
> Thanks. This is strange
> 
> What if you try the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? This will also have a fresh set of extensions and users settings which may fix this

Ooh. We have success:

<img width="1620" alt="Screenshot 2023-07-18 at 6 40 38 PM" src="https://github.com/mjbvz/vscode-markdown-mermaid/assets/2982494/f5a8140c-7886-4203-8935-c5a40cc2bab9">

Though, now it's going to get to me that it's in...mono? I wonder if there's a way to get the sort of nice lilac color I see on GitHub:

<img width="788" alt="Screenshot 2023-07-18 at 6 41 13 PM" src="https://github.com/mjbvz/vscode-markdown-mermaid/assets/2982494/67795752-e9ac-4d75-9b26-1819ff40687c">

And, of course, I have to figure out how I can get all my extensions from the Stable to the Insiders...

**Comment by mjbvz** [comment]
Glad it works

It's somewhat unlikely (but always possible) that insiders itself fixed things. More likely one of the extensions or settings you have in stable was causing issue. Try going through those again to see if you can track down the root cause in case anyone else hits this

**Comment by mathomp4** [comment]
ooh. I might have found it! I started adding in my Stable extensions one-by-one and when I installed--or rather enabled--Markdown Shiki:

https://marketplace.visualstudio.com/items?itemName=bierner.markdown-shiki

it failed!

Maybe this will help you figure something out?

**Comment by Aze1339** [comment]
I'm experiencing the same issue I have uninstalled every extensions, restarted visual studio code and end up with the same issue.

**Comment by mjbvz** [comment]
@Aze1339 Please open a new issues with some example markdown that shows the problems
