### ISSUE TITLE
Upgrade to Mermaid 10.3.x

### ISSUE THREAD

**Issue by ms-xy** [mjbvz/vscode-markdown-mermaid#212]
Mermaid 10.3.0 adds, among other improvements and fixes, `create participant` and `create actor` functionality for sequence diagrams, which is quite useful in order to keep sequence diagrams tidy.

**Comment by cvharris** [comment]
also includes the new `sankey` diagramming ability

**Comment by potsed** [comment]
Many new, non-breaking enhancement to the mermaid library. Please upgrade.

**Comment by TonyBrookILSTU** [comment]
Throwing my voice in on this one. I don't know what it would plug in the newest version of Mermaid, but I need this functionality before any of my other extensions for syntax highlighting and the rest mean anything.
