### ISSUE TITLE
gantt milestone date calculation wrong

### ISSUE THREAD

**Issue by tsing-hsu-nexperia** [mjbvz/vscode-markdown-mermaid#215]
gantt
    tickInterval    4week
    dateFormat      YYYY-MM-DD
    axisFormat      %Y-%m-%d
    start       : milestone, m1, 2023-08-07, 1d
    30 day      : milestone, m2, after m1, 30d
    task1       : active, a1, after m1, 30d

**Comment by mjbvz** [comment]
What is wrong?

Also make sure to retest in version 1.21 of this extension which includes a new mermaid version

**Comment by mjbvz** [comment]
Closing as not actionable without more info
