### ISSUE TITLE
Basic support for fontawesome not working

### ISSUE THREAD

**Issue by Champitoad** [mjbvz/vscode-markdown-mermaid#22]
Based on [the official documentation](https://mermaidjs.github.io/flowchart.html), it should be possible to include fontawesome icons in flowchart diagrams using the syntax `fa:#icon class name#`. However the icons aren't rendered on my computer:

### Expected behaviour

```mermaid
graph TD
    fa:fa-check
```

![screenshot_2018-09-24_20 54 03](https://user-images.githubusercontent.com/910976/45972466-105e8200-c03c-11e8-9d5b-5a484466d5c5.png)

### Actual behaviour

![screenshot_2018-09-24_21 04 04](https://user-images.githubusercontent.com/910976/45972967-6f70c680-c03d-11e8-9f87-2ba575cc8cdf.png)

**Comment by robie2011** [comment]
same issue. I used option `--cssFile fontawesome_all.css` to include the font awesome css from https://use.fontawesome.com/releases/v5.7.1/css/all.css

**Comment by MrBramme** [comment]
If you want to visually add it to your markdown files in visual studio code, you can add the fontawesome css to markdown styles in your settings.
so, open settings, and in the markdown section search for styles. In there press "add" and insert the link to the css file. for example https://use.fontawesome.com/releases/v5.7.1/css/all.css
that'll do the trick

**Comment by MrBramme** [comment]
Opened a pull request with this included into the readme: https://github.com/mjbvz/vscode-markdown-mermaid/pull/38

**Comment by mjbvz** [comment]
Sounds like adding the documentation in #38 was the correct fix
