### ISSUE TITLE
Cannot change entity color in erDiagram

### ISSUE THREAD

**Issue by nos-nakagawa** [mjbvz/vscode-markdown-mermaid#222]
I'm writing erDiagram with mermaid in markdown text.
I want to change color of a certain entity in preview, but I can't.
How can I change it?

(example erDiagram code. Ofcource I can preview it.)
```
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

I tryed adding below codes under example code to change CUSTOMER color, but all of them returns error.
```
1. 
class CUSTOMER {
  fill:#FFDDDD;
}

2.
CUSTOMER {
  color: "#FFDDDD" 
}

3.
classDef customerStyle fill:#FFDDDD;
class CUSTOMER customerStyle;

4.
classDef customerStyle fill:#FFDDDD;
CUSTOMER:::customerStyle

```

**Comment by mjbvz** [comment]
> I tryed adding below codes

Is this something mermaid supports? Can you please share the full text of a diagram that mermaid renders correctly but this extension does not

**Comment by mjbvz** [comment]
Closing as not reproducible
