### ISSUE TITLE
Mermaid Flow Chart Box Sizing Issue #56

### ISSUE THREAD

**Issue by MarcPhilippeJoly** [mjbvz/vscode-markdown-mermaid#229]
Following of Mermaid Flow Chart Box Sizing Issue #56 closed too early.
The boxes don't take font-size into account at resizing.

Assign any font-size attribute superior to 12pt to any box to reproduce.

**Comment by mjbvz** [comment]
Please share example diagram code too

**Comment by mjbvz** [comment]
Closing as more info needed
