### ISSUE TITLE
Diagram is not working

### ISSUE THREAD

**Issue by mjbvz** [mjbvz/vscode-markdown-mermaid#230]
> Hi,
> 
> This is an example of what is no t working for me :
> 
> Code:
> 
> `
> 
> '''mermaid
> 
> 
> 
>   graph TD;
> 
>       A-->B[far:fa-window-maximize B];
> 
>       A-->C;
> 
>       B-->D;
> 
>       C-->D;
> 
> 
> 
> '''
> 
> `
> 
> Render:
> 
> ```mermaid
> 
>   graph TD;
> 
>       A-->B[far:fa-window-maximize B];
> 
>       A-->C;
> 
>       B-->D;
> 
>       C-->D;
> 
> ```
> 
> 
> 
> I hope this helps.
> 
> Thanks
> 
>  

 _Originally posted by @Vince-perso in [#209](https://github.com/mjbvz/vscode-markdown-mermaid/issues/209#issuecomment-1844959829)_

**Comment by RokeJulianLockhart** [comment]
https://github.com/mjbvz/vscode-markdown-mermaid/issues/230#issuecomment-1845950644

@mjbvz, might @Vince-perso be afflicted by https://github.com/mjbvz/vscode-markdown-mermaid/issues/239#issue-2116460124?

**Comment by mjbvz** [comment]
Closing as waiting for more info from the original poster
