### ISSUE TITLE
Export md file as html or pdf

### ISSUE THREAD

**Issue by Yadvo** [mjbvz/vscode-markdown-mermaid#231]
Hi!

Great stuff! This is a feature request. For use case context, I am a business analyst who uses this to render the project documentation, before I commit it to Azure Devops wiki.

However, I am struggling with exporting md files with mermaid diagrams, delimited by Azure Devops ":::" convention into pdf / html files. My non-technical stakeholders sometimes request the documentation to be provided in a hard copy (mainly pdf files). So far, I have not found a way to properly create pdf files with the ":::" delimiter notation.

It would be great if this extension also allowed to convert the md files into pdf/html files, with mermaid diagrams using the ":::" delimiters!

**Comment by mjbvz** [comment]
This extension only provides mermaid rendering support. Exporting the entire markdown preview would be a better fit for another extension
