### ISSUE TITLE
vs code for linux preview does not work with ```mermaid only with :::mermaid

### ISSUE THREAD

**Issue by wege22** [mjbvz/vscode-markdown-mermaid#233]
Hi,

I am using mermaid with "gitea" (only \``` works) and "vs code" (only \::: works) ... 
As mentioned by the documentation \``` should also work.
![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/156713424/ea35faa6-7316-4c46-8faf-13e3d427ad67)

Any suggestions - thanks in advance

**Comment by wege22** [comment]
### **Additional information:**
___
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Datum: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
Betriebssystem: Linux x64 6.1.64-08962-g29b897fe339a
___
Language: german
___
Markdown Preview Mermaid Support v1.21.0
___
OS: ChromeOS Beta 121 / Debian bookworm 12.4

**Comment by mjbvz** [comment]
Works fine for me

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/73ffc6fe-a801-47de-a966-f885d0de168a)


Can you share the full text of a file with this issue?

**Comment by wege22** [comment]
Hi, thanks for your respone ... so the file is:
![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/156713424/7322d2f0-9a16-4a33-bc2d-1943c188b99c)
___
:::mermaid
flowchart LR
    A --> B
:::

~~~mermaid
flowchart LR
    A --> B
~~~

```mermaid
flowchart LR
    A --> B
```
____

I've read some comments about vscode in azure to have some kind of problem, also eventually the german lamguage might cause problems ... file below ...
[mermaid_vscode.md](https://github.com/mjbvz/vscode-markdown-mermaid/files/13981619/mermaid_vscode.md)

**Comment by wege22** [comment]
**SOLVED**
I've found the solution - I've got an other markdown plugin also active which interferred with your extension.
markdown-higlightjs - Adds highlight.js mardown-it plugin to VSCode
