### ISSUE TITLE
Request: Please update to Mermaid v10.7.0+

### ISSUE THREAD

**Issue by noppej** [mjbvz/vscode-markdown-mermaid#234]
Hi. I'm running into this issue (referenced on https://mermaid.js.org/syntax/sequenceDiagram.html#activations).

```
If an error of the following type occurs when creating or deleting an actor/participant:

The destroyed participant participant-name does not have an associated destroying message after its declaration. Please check the sequence diagram.

And fixing diagram code does not get rid of this error and rendering of all other diagrams results in the same error, then you need to update the mermaid version to (v10.7.0+).
```

I'd be happy to PR, if you can give me some pointers to the process.

**Comment by wuleninja** [comment]
Hi everyone ! Thanks for this great plugin. I'd even say regarding this issue: `v10.8.0` would be great, since it brings block diagrams! :)
