### ISSUE TITLE
Font awesome not showing in preview?

### ISSUE THREAD

**Issue by ndland** [mjbvz/vscode-markdown-mermaid#236]
I followed the readme, and I added `markdown.styles` as such:

```json
{
  "markdown.styles": [
    "https://use.fontawesome.com/releases/v6.5.1/css/all.css"
  ],
}
```
However, I don't see the icons, please see below:
<img width="935" alt="image" src="https://github.com/mjbvz/vscode-markdown-mermaid/assets/4358059/cce2180f-8cba-4c53-80f3-75e37df7d8d4">

What gives?

**Edit:** adding diagram as text, for reference: this is the example from the README

```md
graph LR
    fa:fa-check-->fa:fa-coffee
```

**Comment by mjbvz** [comment]
Please share that diagram as text

**Comment by mjbvz** [comment]
The readme shows how to load the font-awesome css: https://github.com/mjbvz/vscode-markdown-mermaid?tab=readme-ov-file#using-custom-css-in-the-markdown-preview

Works fine for me after adding this
