### ISSUE TITLE
Cannot use 3 x backticks to delimit code block; must use `:::`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-markdown-mermaid#239]
```.MD
::: mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
:::
```

...renders as a graph, yet:

~~~.MD
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
~~~

...does not.

**Comment by mjbvz** [comment]
Works fine for me. Are you sure it's not one of your other extensions interfering? 

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/83e86331-e199-430f-9ff2-b70d58cd1d7f)

**Comment by mjbvz** [comment]
Seems like https://github.com/mjbvz/vscode-markdown-mermaid/issues/233#issuecomment-1917942305

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/239#issuecomment-1928616931

I'll check. That's a good idea, @mjbvz. It might take me a while, but I'll get back to you.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/239#issuecomment-1928636932

It works for me now. I don't know whether I ever ascertained why.
