### ISSUE TITLE
Support for default classDef

### ISSUE THREAD

**Issue by c-dante** [mjbvz/vscode-markdown-mermaid#24]
Seems that class support is there, but mermaid has `classDef deafult ...` that applies to all nodes.

> ### Default class
> If a class is named default it will be assigned to all classes without specific class definitions.
> `    classDef default fill:#f9f,stroke:#333,stroke-width:4px;`

It's [under flowchart](https://mermaidjs.github.io/flowchart.html)

**Comment by mjbvz** [comment]
Can you please share a full example of what the markdown would look like for this?

**Comment by c-dante** [comment]
```md
graph TD
  A --> B;
  B --> C;
  classDef default fill:#f9f,stroke:#333,stroke-width:4px;
```

That should apply the class given there to all nodes that do not have a class specified.

**Comment by mjbvz** [comment]
Seems to work fine now, likely from picking up a new mermaid version
