### ISSUE TITLE
Support `sequenceDiagram`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-markdown-mermaid#240]
https://mermaid.js.org/syntax/examples.html#basic-sequence-diagram doesn't work.

**Comment by mjbvz** [comment]
How so?

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/ad36873e-f0e8-4af3-a9b2-93d6ec0012b2)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/240#issuecomment-1928615881

@mjbvz, I've been using

```
::: mermaid
:::
```

due to https://github.com/mjbvz/vscode-markdown-mermaid/issues/239#issue-2116460124. Does that make any difference for you? If not, I have no idea of why this isn't working for me.

**Comment by mjbvz** [comment]
Yes works fine with `:::` too. Maybe one of your other extensions?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/240#issuecomment-1928640551

I expect so. I'll get back to you about this too, @mjbvz.
