### ISSUE TITLE
Support Markdown inside diagram.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-markdown-mermaid#241]
Per https://github.com/mermaid-js/mermaid/issues/1844#issuecomment-1054069105 and https://github.com/mermaid-js/mermaid/issues/1844#issuecomment-911548906, consider a complex flowchart like:

```.MD
::: mermaid
flowchart
    n1["**Tumult**\nThe local and national government must be viewed comprehensively as incompetent in order for extensive reform to occur.\n"]
	n2["Leader Appearance\nIn order for the implementation to be swift and consistent, the leader must be a competent orator and instill confidence within each sector of the populace differently; his skillset must appear to demonstrate knowledge of the struggles of the country on a personal level.\n"]
	n1 --- n2
	n3["Party Formation\nAlthough ideologically, the lone restructurer might be a romantic concept, it is not practical. In fact, the comprehensive existence and integration of the legal political party as a quasi-necessity into current democratic systems of governance may operate favourably, especially in those of proportional representation.\nHowever, systems which utilize first-past-the-post may be more difficult. This is why tumult is a prerequisite — it shall significantly weaken the duopolic parties temporarily, providing the chance for an incumbent to pass the threshold necessary to become a fledgling third, and eventually replace one of the counterparts.\n"]
	n2 --- n3

:::
```

...would significantly benefit from being able to make the titles bold. However, are we waiting on https://github.com/mermaid-js/mermaid/issues/1580#issue-666190829 for this?

**Comment by mjbvz** [comment]
Yes this extension only renders normal mermaid diagrams. I don't want to add support for a feature which mermaid doesn't support out of the box

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/241#issuecomment-1928615019

And I expect that were this added to Mermaid, it would automatically be functional in this due to your usage of the official library? Or, if not, you would consider supporting it?
