### ISSUE TITLE
Multi-line `.HTML` comment, in numbered list, after Mermaid section, breaks rendering.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-markdown-mermaid#242]
Try:

```.MD
::: mermaid
flowchart
    n1["Rectangle"]

:::

1.	**Test**

	<!--

	test -->

```

This was the absolute minimum I could create which would still break the renderer, per:

> ![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/42837531/63cd5827-93b4-41ed-9aed-4f9df7bb51c0)

To demonstrate,

1.	```.MD
	::: mermaid
	flowchart
	    n1["Rectangle"]
	
	:::
	
	
	```
	
	and
	
1.	```.MD
	::: mermaid
	flowchart
	    n1["Rectangle"]
	
	:::
	
	1.	**Test**
	
	```

in contrast, render correctly.

**Comment by mjbvz** [comment]
Seems ok to me


![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/da9d2765-d496-4d66-98d7-e41625235b32)

 What about with other extensions disabled?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/242#issuecomment-1928637670

I swear, whatever extension is causing this mayhem I will nuke from orbit, @mjbvz.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/242#issuecomment-1928637670

@mjbvz, I'm still seeing this, using

~~~MD
```mermaid
flowchart
    n1["Rectangle"]

```

1.	**Test**

	<!--

	test -->

~~~

but not the aforementioned working versions

~~~MD
```mermaid
flowchart
    n1["Rectangle"]

```

<!--

test -->
~~~

~~~MD
```mermaid
flowchart
    n1["Rectangle"]

```

1.	**Test**

~~~

Do you have a solution for https://github.com/microsoft/vscode/issues/81950#issue-502557730? I have a *lot* of extensions (albeit few which should affect anything like this).
