### ISSUE TITLE
Block diagram is not recognised

### ISSUE THREAD

**Issue by pushkarppandit** [mjbvz/vscode-markdown-mermaid#244]
### Expected behaviour

```mermaid
block-beta
  a b c
```
This should ideally render the below since this should support mermaid version 10.8.0
<img width="95" alt="image" src="https://github.com/vstirbu/vscode-mermaid-preview/assets/30230209/87bc744c-37d1-47ec-bfb3-227682545584">

vscode theme is dark

### Actual behaviour
Getting the error in markdown preview
```
UnknownDiagramError: No diagram type detected matching given configuration for text: block-beta
  a b c
```

**Comment by mjbvz** [comment]
![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/302098d8-7b97-4efb-8637-097a391ccce7)

What extension version are you using?
