### ISSUE TITLE
Support HTML in Markdown strings.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-markdown-mermaid#246]
Per https://github.com/orgs/mermaid-js/discussions/5329#discussioncomment-8646264, this should be possible, yet all I see is “*Unsupported Markdown:* [*code*, *break*, etc.]”.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/246#issue-2163953175

This also appears at https://github.com/mermaid-js/mermaid-live-editor/issues/1411#issue-2163963447, so like https://github.com/mjbvz/vscode-markdown-mermaid/issues/245#issuecomment-1964280841, this may be better reported at https://github.com/mermaid-js/mermaid/issues/new?assignees=&labels=Status%3A+Triage%2CType%3A+Bug+%2F+Error&projects=&template=bug_report.yml.

**Comment by mjbvz** [comment]
Please share the source text of example diagram that demonstrates the issue

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/246#issuecomment-2176919789

@mjbvz, I did provide an example in the linked issues, but I understand you not wanting to trawl through them:

> ~~~MD
> ```mermaid
> flowchart TD
>     test["`*test*<br>`"]
> ```
> ~~~

which renders as

> ![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/42837531/eb5293df-0433-48f7-8274-5fe80456a18f)

in `code-insiders-1.91.0-1718700915.el8.rpm`.

**Comment by mjbvz** [comment]
I think this was fixed. Here's what I see for that diagram now:

![Image](https://github.com/user-attachments/assets/ef3462a1-04cc-4a92-a65b-9b30830a566d)

**Comment by RokeJulianLockhart** [comment]
Works for me too, @mjbvz. Thanks!
