### ISSUE TITLE
Elk renderer not working on 1.22.0 when a subgraph is empty

### ISSUE THREAD

**Issue by Alexandre-SCHOEPP** [mjbvz/vscode-markdown-mermaid#249]
Hi !

As I mentioned in #223 I have an issue with this extension. When using the `elk` renderer when a subgraph is empty, I get the following error : `Cannot read properties of null (reading 're')`

Here is my minimum reproducible example:

```markdown
## Works

:::mermaid
%%{init: {"flowchart": {"defaultRenderer": "dagre"}} }%%
flowchart TD
subgraph A
end
:::
```
```markdown
## Does not work
:::mermaid
%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
flowchart TD
subgraph B
end
:::
```

Here's a screenshot : 
![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/154252112/6ef28855-fe73-4274-acd3-140ff9cdfbb2)

Please note that I am aware that this may be an issue with mermaid itself.
Running the code in 1.21.0 or 1.20.0 yields instead `Cannot read properties of null (reading 'he')`, and I think I had it work once on a graph I can't find in 1.21.0 where it didn't in 1.22.0, but I since deleted it as it was too complex for a minimum viable exemple (😓)

**Comment by mjbvz** [comment]
Seems like the same error happens [in the mermaid live editor](https://mermaid.live/edit#pako:eNo9jUEOwjAMBL8SWcqtL8gR9QXA0RfTuDSicSvjCKEofydQieOudmYrTFtkCOB9TZIsuIowr9trWkgN4Zcjz1RWO7NEVtZvi8DrA6E117xH-RPuOqI8y-2utC_uhNIZGCCzZkqx_1QU12lbOPMhiqTdhNL6joptl7dMEEwLD1D2SMZjou7LR9k-ewA9oQ)

Please file this against Mermaid JS directly so they can take a look
