### ISSUE TITLE
what is fsdaf command? is it typo?

### ISSUE THREAD

**Issue by productinfo** [mjbvz/vscode-markdown-mermaid#25]
https://github.com/mjbvz/vscode-markdown-mermaid/blob/0ea3d0b48dcfa06edc0367afff3b34eaf9d1b3c5/package.json#L33

https://github.com/mjbvz/vscode-markdown-mermaid/blob/0ea3d0b48dcfa06edc0367afff3b34eaf9d1b3c5/package.json#L34

**Comment by mjbvz** [comment]
I've un-fsdaf the fsdaf with 1.1.1
