### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by MrBjorn** [mjbvz/vscode-markdown-mermaid#252]
I cant get the links working, bug? Its popup-menus. The syntax is:

::: mermaid
sequenceDiagram
    participant A
    links A: label @ url
:::

**Comment by mjbvz** [comment]
What isn't working? Seems to match mermaid.live:

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/6f41c6b9-c009-49c5-aba1-bcbb7400c3d7)

**Comment by mjbvz** [comment]
Closing as unclear what the issue is
