### ISSUE TITLE
Auto scrolling on larger files causing chaos

### ISSUE THREAD

**Issue by WarpedLogik** [mjbvz/vscode-markdown-mermaid#255]
Hi, have started using your addon and think it's great however I'm trying to work on a larger sequence diagram ~120 lines and the way the auto scrolling is handled is making it pretty much unusable.

If remaining at the top of the file it's fine, both sides line up.

If I start scrolling the .md file the preview jumps to blank space at the bottom of the diagram and doesn't return unless I either scroll the diagram or scroll back to the top of the .md file.

Having to scroll back up the preview to see the bit I'm working on is slow but usable but if I want to work on the bottom part of the .md file the act of scrolling the preview back to the point where I can see the part of the diagram I need forces the .md file to scroll back to the top. This ends up as a dance between either being able to see the part of the .md file I'm working on or the part of the diagram I'm working on.

Hopefully this explanation helps, if you need any more info please shout,
Cheers

**Comment by mjbvz** [comment]
Please share an example file which causes this

**Comment by mjbvz** [comment]
Closing as not actionable without steps to reproduce

**Comment by giulianob** [comment]
I am experiencing this too. 
1. Create a large diagram ( [sample.md](https://github.com/user-attachments/files/16088669/sample.md) )
2. Action \>Markdown: Open preview to the side
3. Scroll the markdown side and you can see the diagram scrolling position jumps either to the beginning/end


https://github.com/mjbvz/vscode-markdown-mermaid/assets/92303/acf6710e-2729-48bf-8c2b-7077a217e1d4

**Comment by valler** [comment]
Can confirm. This extension effectively breaks bidirectional scroll sync. When scrolling the preview, both the editor and the preview jump unpredictably.
