### ISSUE TITLE
Not visualisations shown after installation

### ISSUE THREAD

**Issue by snuup** [mjbvz/vscode-markdown-mermaid#265]
The markdown preview does not render graphs, it just shows the text. Are there any further installation requirements?

**Comment by mjbvz** [comment]
Please share:

1. VS Code and ext version
2. An example document showing this not working

**Comment by sktpin** [comment]
I might have the same problem, or I'm missing something - I don't have a preview window showing up, do I need to explicitly open it somewhere?
I created a file flowchart.mmd and opened it in vscode, put the content below in it.
There is no icon for this plugin showing on the left bar, where some other plugins are showing.
I also installed another extension for syntax highlighting Mermaid, which works (the one by Brian Pruitt-Goddard).

VScode Version: 1.92.2
This extension: v1.23.1

```mermaid
flowchart LR
  A --> B
```

**Comment by mjbvz** [comment]
> `flowchart.mmd`

This extension supports VS Code's built-in markdown preview. Other markdown flavors such as `mmd` may have their own extensions that provide their own preview

However `There is no icon for this plugin showing on the left bar, where some other plugins are showing.` also suggests that this extension has not been installed properly


---

Closing this issue as we need more info from @snuup to investigate. My best guess is that it's a user issue (such as wrong language for the text file) or a conflict with another extension
