### ISSUE TITLE
Not support classDef in stateDiagram

### ISSUE THREAD

**Issue by mosuzi** [mjbvz/vscode-markdown-mermaid#271]
With `classDef`:
![image](https://github.com/user-attachments/assets/d2beceb5-65ae-4caa-bffa-7519961ec910)

Without `classDef`:
![image](https://github.com/user-attachments/assets/8adbd44c-91af-4611-a890-b32032f28bd2)

Maybe it's because of a lower mermaid version and hope support latest mermaid.

**Comment by mosuzi** [comment]
Here is a case copied from mermaid official.

```
   stateDiagram
   direction TB

   accTitle: This is the accessible title
   accDescr: This is an accessible description

   classDef notMoving fill:white
   classDef movement font-style:italic
   classDef badBadEvent fill:#f00,color:white,font-weight:bold,stroke-width:2px,stroke:yellow

   [*]--> Still
   Still --> [*]
   Still --> Moving
   Moving --> Still
   Moving --> Crash
   Crash --> [*]

   class Still notMoving
   class Moving, Crash movement
   class Crash badBadEvent
   class end badBadEvent
```

**Comment by mjbvz** [comment]
Seems to works fine for me in 1.25.0 which bumped the Mermaid version
