### ISSUE TITLE
Text overflows box in flowchart

### ISSUE THREAD

**Issue by pjsvis** [mjbvz/vscode-markdown-mermaid#28]
![mermaid](https://user-images.githubusercontent.com/729613/56949003-b7068600-6b29-11e9-9af2-f81b77938862.PNG)

The above was generated from 

```
   bFindOut -- continue --> cWhatHappened(S3 What Happened) 
    cWhatHappened -- continue --> dCategorise(S3a Categorise)
```

The text seems to overflow the flowchart box.

Is there a style sheet that I can weak to fix this?

**Comment by mjbvz** [comment]
Does this happen when you run mermaid from the command line and view the output outside of VS Code?

**Comment by pjsvis** [comment]
Hi there Matt, I am not sure how to run mermaid from the command line but I will see if can in the morning.

More later....

**Comment by mjbvz** [comment]
https://github.com/mermaidjs/mermaid.cli

**Comment by 4lph4-Ph4un** [comment]
Hi! Having the same issue. On CLI output the text overflow does not seem to happen.

**Comment by 4lph4-Ph4un** [comment]
Anything new on this?

**Comment by mjbvz** [comment]
Closing as likely an upstream mermaid issue

**Comment by tedlindstrom-canea** [comment]
Hi, I'm using v1.27.0 and VS Code 1.99 I have the same issue. Is it just me or..?

```mermaid
graph TB;
    subgraph Far far away
    A[behind the word mountain] --> B[far from the countries Vokalia and Consonantia];
    end
```

![Image](https://github.com/user-attachments/assets/00cc8c1f-f365-4711-9696-875ae8b6d3b7)
