### ISSUE TITLE
All lines are arrows now

### ISSUE THREAD

**Issue by DirkRR** [mjbvz/vscode-markdown-mermaid#280]
System:
- Windows 10 Pro, Version 22H2 (10.0.19045)
- VS Code, Version 1.93.0
- Node.js, Version 20.15.1

Since the last update (1.24.0), all lines are displayed as arrows.

(partial) code:
    parameter-.-Options
    parameter-.-label

Result:
![mermaid_issue](https://github.com/user-attachments/assets/990fe31a-eed6-48b7-ae97-c309a8df5301)

**Comment by mjbvz** [comment]
Please share the text of a diagram which demonstrates this issue

**Comment by msl0** [comment]
Hi,
@mjbvz I have the same issue
Markdown Preview Mermaid Support v1.25.0
VS Code 1.92.2 (user setup)
Node.js: 20.14.0
OS: Windows_NT x64 10.0.22631

mermaid
graph TD
    A1---B1
    A2-->B2
    A3-.-B3
    A4-.->B4

**Comment by mjbvz** [comment]
What is it supposed to look like? Seems like [mermaid.live shows arrows being used everywhere too](https://mermaid.live/edit#pako:eNolzb0KwzAMBOBXMZqjQn4mD4GavEE7ahGxGofWTnDsoYS8ewXdvoM77oR58wIWlsx7MM-J0r1FRNcqOsTRdYoeb-h6xaAY3QANRMmRV6_Lk5IxBCVIFAKr9JzfBJQu7XEt2-ObZrAlV2kgb3UJYF_8OTTV3XORaWW9j__K9QOMfy4x)

**Comment by mjbvz** [comment]
That shows everything as arrows:

![Image](https://github.com/user-attachments/assets/fcaccb9f-5150-4384-9aed-4d4bf984513b)

That means this is a mermaid issue. Please file an issue against them
