### ISSUE TITLE
Mermaid flowchart displayed incorrectly after updating to version 1.24.0

### ISSUE THREAD

**Issue by StefanoMpmc** [mjbvz/vscode-markdown-mermaid#283]
System:

Windows 10
VS Code, Version 1.93.0

Since the last update (1.24.0), flowchart displayed incorrectly.

~~~md
```mermaid
flowchart LR;

    A10("📁 AxX-ZQ-Accessories #nbsp; #nbsp; #nbsp; #nbsp;")

        A10 --> A10_B10("📁 3rd-Party #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp;")
            A10_B10 --> A10_B10_C10("📁 1-Wire #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp;")
            A10_B10 --> A10_B10_C20("📁 FTDI #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp; #nbsp;")

classDef styleOrganization fill:#F5B8A4,stroke:#E97132,stroke-width:2px,color:#000000,font-weight:bold
classDef styleRepository fill:#9CCFF5,stroke:#0F9ED5,stroke-width:2px,color:#000000,font-weight:bold
classDef styleSubFolder fill:#A8D5A0,stroke:#4EA72E,stroke-width:2px,color:#000000,font-weight:bold

class A10 styleOrganization;
class A10_B10 styleRepository;
class A10_B10_C10,A10_B10_C20 styleSubFolder;
```
~~~

Result:
![image](https://github.com/user-attachments/assets/fe726bce-1d3e-4f16-97de-c2596b502d0f)

**Comment by mjbvz** [comment]
Seems to match the [rendering on mermaid.live](https://mermaid.live/edit#pako:eNq1k-FqgzAQx19F4pcNFKyttI0wsFVhMNjWDjaGUFKNGqpGkkjrSj_sGfYAe8U9wqy4VlwZlG335XJ34X7_JJct8GmAAQRhQtd-jJiQbmaml3mZVJnV0y488PH-9ipZmyf1-V61fB9zThnBXJKzJc_Nk84Dl189mj6Sql7t_WJy7NlngXpXIcufWp3tarbUsobaVrCYHlX01EfC8J9KOEuJflDiPtjX_6Hj5Nv4CeLcxqHERZngWxahjLwgQWgmhSRJoOwak5E1ULhgdIWh7IyHvb7ehOqaBCKGer5RfJpQBmWtNiWkmVDXmESxgEuaBF3ODOeUE0FZ2VDG06nrGgeK5o4d2_gtZV4s3SqNWQOxRrZhaQfIwLGGunM-pMHU4_zt1sxWtX7kznm79f0IKq0h6Cg3gQJSzFJEgup3bvdz5AER4xR7AFbLALGVB7xsV-1DhaDzMvMBFKzACmC0iGIAQ5TwKiryAAlsExQxlDbZ3SfeSkXi)

Please try filing an issue against Mermaid directly for this

**Comment by StefanoMpmc** [comment]
Thanks for reply. Issue sent directly to Mermaid site.

In any case I can't use version 1.24.0 (not even 1.25.0)
