### ISSUE TITLE
Self loops do not work

### ISSUE THREAD

**Issue by jacob-tye** [mjbvz/vscode-markdown-mermaid#284]
![image](https://github.com/user-attachments/assets/30396c22-a5d1-4147-8c80-53cac451c914)
      
      gives
      
![image](https://github.com/user-attachments/assets/c9b942ed-905e-477b-a4e9-6093e55cda2a)
 
on mermaid live it works
![image](https://github.com/user-attachments/assets/b804bb90-aa72-4172-bdd5-6bd4ca42536b)

Removing the self loops makes the code work
![image](https://github.com/user-attachments/assets/ec6afee7-045f-4914-9175-cfe2d296eaa2)

![image](https://github.com/user-attachments/assets/32e27cd7-b578-4b78-9a7d-ac409937a16d)

**Comment by jobatabs** [comment]
This is an issue from upstream Mermaid, this is fixed in Mermaid 11.2.0. Maintainer needs to bump version to 11.2.

**Comment by sdevilliers** [comment]
How does one upvote an issue? I am having this problem too

**Comment by mjbvz** [comment]
Confirmed our rendering seem to [match what mermaid.live shows](https://mermaid.live/edit#pako:eNpNjL0KAjEQhF8lTH1BbFOIhaWVttssl70fvCSSSzgk5N1NsHGKYYb5mIIxWIHBtIVjXDgmdX-QV11J9lQK4drDqdvqZ0Ktf7vWinAmKK0vvWOAk-h4te2zdJCQFnFCMC1aji8C-do4zik8P36ESTHLgBjyvMBMvO2t5bflJLeV58juh9QvGDY5Rg)

If there are still issues with this, please test on https://mermaid.live first and then file an issue against mermaid directly

**Comment by jacob-tye** [comment]
Confirmed it is working
