### ISSUE TITLE
Compatability with WebSequenceDiagrams' syntax "End Note" and "Title"

### ISSUE THREAD

**Issue by DevChive** [mjbvz/vscode-markdown-mermaid#29]
As a user, I would like to be able to seamlessly import my designs from [WebSequenceDiagrams.com](https://www.websequencediagrams.com/) and use the same syntax.  For instance, i cannot use multi-lined noted using ``Note Over`` and ``Note End`` to end the block, as well as, ``Title`` which displays the title of the diagram in the top center.

## Suggested Feature
This would allow us to create a title for the diagram, and have multi-lined notes.

```mermaid
sequenceDiagram
    title WHAT IS THIS DIAGRAM
    Alice->>Bob: Hello Bob, how are you?
    note over Alice,John
       A typical interaction
       And a second line for talking points
    end note

    alt is sick
        Bob->>Alice: Not so good :(
    else is well
        Bob->>Alice: Feeling fresh like a daisy
    end
    opt Extra response
        Bob->>Alice: Thanks for asking
    end
```

**Comment by mjbvz** [comment]
Is this supported by [mermaid](https://mermaidjs.github.io)?

**Comment by mjbvz** [comment]
Closing this as it should be a feature request against mermaid instead
