### ISSUE TITLE
"Markdown Preview Mermaid Support" does not work with "Markdown All in One" extension

### ISSUE THREAD

**Issue by peterdanwan** [mjbvz/vscode-markdown-mermaid#293]
### What's the problem

If the user has the [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) extension installed, the `Print current document to HTML` command from [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) produces a lot of extra text in the HTML.

This video shows how the `Markdown All in One` extension works fine when `Markdown Preview Mermaid Support` is disabled:

https://github.com/user-attachments/assets/328b9051-3e49-4f58-8c43-d2b239ba783d

This video shows how the `Markdown All in One` produces a lot of text in the resultant HTML file if `Markdown Preview Mermaid Support` is enabled:

https://github.com/user-attachments/assets/8c91d4bb-45f8-4f78-9a9d-373ead29001b

This video shows another extension [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) converting the markdown to html properly with the `Markdown Preview Mermaid Support` extension enabled:

https://github.com/user-attachments/assets/d32577fe-5f1f-4b06-9190-1ad0b733cf87

### What's the expected result

The expected result would be that the `Print current document to HTML` command from `Markdown All in One` works even if the `Markdown Preview Mermaid Support` extension is enabled.

### How to reproduce

1. Enable [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
2. Enable [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
3. Create a markdown file
4. Use the `Print current document to HTML` command.

### Other information
NOTE: I have logged another issue with `Markdown All in One` over [here](https://github.com/yzhang-gh/vscode-markdown/issues/1476). I would love to work on trying to resolve this issue and was wondering if I could receive some pointers! I'm new to open-source development, and would love to assist in fixing this issue.

**Comment by mjbvz** [comment]
This extension only officially works with VS Code's built-in markdown extension. Any issues related to markdown all in one should be will need to be handled on their side
