### ISSUE TITLE
Fenced code blocks not working

### ISSUE THREAD

**Issue by nha4601** [mjbvz/vscode-markdown-mermaid#296]
![Screenshot 2024-11-14 095228](https://github.com/user-attachments/assets/a4a3a534-c6a6-4966-b490-869eef24c2e2)

**Comment by mjbvz** [comment]
Please share your vscode version and extension version

**Comment by mjbvz** [comment]
Does it reproduce if you disable other extensions. Markdown All in One specifically has conflicted with this extension in the past

**Comment by nha4601** [comment]
Disabled all extensions and works as expected.

I tried re-enabling one-by-one - there seems to be an issue with [mathpix.vscode-mathpix-markdown extension](https://github.com/mathpix/vscode-mathpix-markdown) causing the problem.

**Comment by mjbvz** [comment]
Thanks for checking. Please file an issue against that extension

**Comment by nha4601** [comment]
Done
