### ISSUE TITLE
Unexpected fillings in interpolate linkStyle

### ISSUE THREAD

**Issue by spbroma** [mjbvz/vscode-markdown-mermaid#31]
After adding `linkStyle default interpolate basis ` parameter, link became filled with black
OS: Windows Server 2008 R2

![image](https://user-images.githubusercontent.com/1898310/64474752-a920db80-d181-11e9-8edf-977696a4aee0.png)

**Comment by mjbvz** [comment]
Does this only happen in VS Code? What if you run the [mermaid cli](https://github.com/mermaidjs/mermaid.cli) on the same file?

**Comment by mjbvz** [comment]
Closing as likely an upstream issue with mermaid
