### ISSUE TITLE
Underscore in elements name and subgraph titles doesn't supported

### ISSUE THREAD

**Issue by GreenRobot777** [mjbvz/vscode-markdown-mermaid#32]
![image](https://user-images.githubusercontent.com/14993551/65448523-2e371080-de63-11e9-91e5-ac2d98b17337.png)

![image](https://user-images.githubusercontent.com/14993551/65448726-b3222a00-de63-11e9-93ca-9925b64057a9.png)

👉 See example code [there](https://gist.githubusercontent.com/GreenRobot777/db4875a122f7c680c297e9d0ecdb1cb5/raw/3bbb2eedfb3fcbd9bb689c49c433d86a2b2ac56d/test-markdown-mermaid.md)

👉 Please, try to test it on https://stackedit.io/app#
It rendering very well:
![image](https://user-images.githubusercontent.com/14993551/65449302-e4e7c080-de64-11e9-9fc8-eddb58808dab.png)

**Comment by mjbvz** [comment]
Repo steps?

**Comment by jaxidian** [comment]
I can reproduce this. I'm trying to use this with some DB tablenames that have underscore in them, which is causing problems. Original post had repro steps but here are is a simple example. I'm failing at getting this code to render correctly, so remove the `>` characters in this example:

```
> **Works**
> ```mermaid
> graph LR
>     A(asdf) --> B(xyz)
>     A(asdf) --> C(qwerty)
> ```
> 
> ---
> 
> **Breaks (should work but does not)**
> ```mermaid
> graph LR
>     A(as\\_df) --> B(xyz)
>     A(as\\_df) --> C(qwerty)
> ```
> ---
> 
> **Breaks (invalid)**
> ```mermaid
> graph LR
>     A(as_df) --> B(xyz)
>     A(as_df) --> C(qwerty)
> ```
```

**Comment by mjbvz** [comment]
Does this only happen in VS Code? What if you run the [mermaid cli](https://github.com/mermaidjs/mermaid.cli) on the same file?

**Comment by mjbvz** [comment]
Closing as what I see in  1.4.1 of this extension (top) seems to match the mermaid live preview (bottom):

![Screen Shot 2019-11-08 at 5 38 18 PM](https://user-images.githubusercontent.com/12821956/68520688-a2304b00-024e-11ea-9022-389795874ca7.png)
