### ISSUE TITLE
Support double-arrowed lines

### ISSUE THREAD

**Issue by jaxidian** [mjbvz/vscode-markdown-mermaid#33]
I'm referring to this feature: https://github.com/knsv/mermaid/issues/123#issuecomment-506639849

Example:

```
graph LR
  A <--> B
```

**Comment by mjbvz** [comment]
Does this only happen in VS Code? What if you run the latest [mermaid cli](https://github.com/mermaidjs/mermaid.cli) on the same file?

**Comment by mjbvz** [comment]
Confirmed our rendering (top) matches what the mermaid live editor shows (bottom):

![Screen Shot 2019-11-08 at 5 33 51 PM](https://user-images.githubusercontent.com/12821956/68520627-f8e95500-024d-11ea-8a00-c58462057fff.png)

**Comment by pendraggon87** [comment]
This doesn't appear to be accurate - the live editor shows both arrows, but Obsidian does not.
![image](https://user-images.githubusercontent.com/2318439/200348853-d092d5f5-aa5f-4510-9223-4051d60f6b4c.png)
