### ISSUE TITLE
Diagram Does Not Render when Remote

### ISSUE THREAD

**Issue by xendren** [mjbvz/vscode-markdown-mermaid#34]
My markdown file is on a remote linux server.  The extension installed fine on the remote host, but it isn't rendering correctly in the previewer.  I just copied and pasted the sample mermaid block from the readme into a new .md file.  Other markdown statements in the file render fine in the previewer.  The diagram, however, just shows "graph TD:" and the other lines as text.  Does it not work remotely, or am I missing some configuration?

**Comment by mjbvz** [comment]
What type of remote are you using? SSH?

Also share your VS Code version

**Comment by xendren** [comment]
Yes.  Using the Remote - SSH extension from Microsoft.  

VS Code version is:
Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by xendren** [comment]
Here is what I am seeing:

![image](https://user-images.githubusercontent.com/7947774/66670459-71dd9880-ec1f-11e9-9985-83615ba10f51.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by xendren** [comment]
I installed the latest Insiders build on another machine, and it renders correctly with a file remote under WSL.  My work machine is connecting to a remote Red Hat server, so it isn't exactly apples to apples comparison.  I will try to update my work machine to Insider build this week and see the results.

**Comment by xendren** [comment]
Ok.  My apologies.  I've made this confusing.  The original issue I encountered was under VS Code 1.39.1 on October 11th.  I just tried it again on the original machine under 1.39.2 that was released on October 15th, and it appears to be working fine.   

On a side note, the problem was still present under the latest Insiders build with a remote markdown file on WSL Ubuntu.  Just an FYI.
