### ISSUE TITLE
Support for Mermaid v.8.4

### ISSUE THREAD

**Issue by J-Setzer** [mjbvz/vscode-markdown-mermaid#35]
Can you please support latest **Mermaid Version 8.4** with new diagram type: state diagram

http://knsv.github.io/mermaid/#/stateDiagram

Thanks!
Kind regards,
Jan

**Comment by mjbvz** [comment]
Please submit a PR. This should be a pretty simple change; see the past mermaid upgrade: https://github.com/mjbvz/vscode-markdown-mermaid/commit/47bb5822524cfb0961c7c4b9d7aef0839d56b0aa

**Comment by MrBramme** [comment]
I've created a pull request for this here : https://github.com/mjbvz/vscode-markdown-mermaid/pull/37

**Comment by MrBramme** [comment]
as it has been merged into version 1.4.0, I believe we can close this one
