### ISSUE TITLE
Configuration to use ::: instead of ```

### ISSUE THREAD

**Issue by fuchsdaniel** [mjbvz/vscode-markdown-mermaid#36]
Hey guys,

Great work on the project. We love to use it.
I have a question:
Is there any configuration that we can change the character that is used to "define" a mermaid diagram?
We use Azure DevOps Wiki and there, to recognize that the "segment" is a mermaid Diagram, they only accept ::: instead of ```, so when we write the markdown in VSCode, we write using ``` and than we need to remember to change to ::: before published.

Thanks in advance,

Daniel

**Comment by mjbvz** [comment]
Not currently. Since this is a new syntax, we would would need a markdown-it extension to parse this grammar as well. Here's an example extension that contributes a markdown-it extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-yaml-preamble

**Comment by fuchsdaniel** [comment]
> Not currently. Since this is a new syntax, we would need a markdown-it extension to parse the ::: blocks. Here's an example extension that contributes a markdown-it extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-yaml-preamble

Thanks for your reply.
I saw your tag about a help wanted. How can we assist with this item, for example?

Regards,
Daniel

**Comment by mjbvz** [comment]
As a first step, create a [markdown-it plugin](https://github.com/markdown-it/markdown-it/tree/master/docs) that can parse `:::` blocks. Once that exists, we can integrate it into this extension

**Comment by fuchsdaniel** [comment]
Thanks. I will be working on it this weekend.

**Comment by tahid-miah-swo** [comment]
Is this something that's been implemented?

**Comment by Bjego** [comment]
Hey guys,
that feature would be cool, so any news so far?

**Comment by lwalker-kforce** [comment]
Bumping this to see if there has been any progress. Would be great to support ::: in Azure DevOps Wiki pages.

**Comment by rafalkasa** [comment]
Any news about support of ::: in Azure DevOps Wiki syntax ?

**Comment by rafalkasa** [comment]
If anyone need this feature I have added PR #76 solving issue with Azure DevOps syntax for mermaid

**Comment by mjbvz** [comment]
Fixed by #76
