### ISSUE TITLE
Please add support for class diagrams

### ISSUE THREAD

**Issue by vasyl-purchel** [mjbvz/vscode-markdown-mermaid#4]
An example of the class diagram is taken from the [mermaid github readme](https://github.com/knsv/mermaid):

```mermaid
classDiagram
    Class01 <|-- AveryLongClass : Cool
    Class03 *-- Class04
    Class05 o-- Class06
    Class07 .. Class08
    Class09 --> C2 : Where am i?
    Class09 --* C3
    Class09 --|> Class07
    Class07 : equals()
    Class07 : Object[] elementData
    Class01 : size()
    Class01 : int chimp
    Class01 : int gorilla
    Class08 <--> C2: Cool label
```
![image](https://user-images.githubusercontent.com/7029408/29367255-37b9c4e0-8294-11e7-9376-3dd29824dd6e.png)

if you try to select the content you can see that text exists there:
![image](https://user-images.githubusercontent.com/7029408/29367302-5c785a30-8294-11e7-969c-38bf0a6ef310.png)

**Comment by mjbvz** [comment]
Here's what I see using the markdown:

~~~markdown

 ```mermaid
classDiagram
    Class01 <|-- AveryLongClass : Cool
    Class03 *-- Class04
    Class05 o-- Class06
    Class07 .. Class08
    Class09 --> C2 : Where am i?
    Class09 --* C3
    Class09 --|> Class07
    Class07 : equals()
    Class07 : Object[] elementData
    Class01 : size()
    Class01 : int chimp
    Class01 : int gorilla
    Class08 <--> C2: Cool label
```
~~~

with 0.0.3 of markdown mermaid:

![screen shot 2017-08-19 at 2 06 48 pm](https://user-images.githubusercontent.com/12821956/29490118-a6933266-84e7-11e7-8c0a-2b83b328f0f4.png)

Please update to out 0.0.3 and let me know if you still see this issue

**Comment by vasyl-purchel** [comment]
cool, it works in v0.0.3, thanks

**Comment by StingyJack** [comment]
For anyone else coming here because this isnt working for them, the underlying mermaid code is particular about ordering of the statements for classDiagram unlike some of the other types. 

For instance, this does not render
```
classDiagram
  MyObject : int Field1
  MyObject <|-- MyDerivedObject
```
But this does
```
classDiagram
  MyObject <|-- MyDerivedObject
  MyObject : int Field1
```

It also wont render if there are any spaces after the `classDiagram` declaration; that needs to be followed  by only a newline.
