### ISSUE TITLE
Feature Request: Port for Azure Data Studio

### ISSUE THREAD

**Issue by codykonior** [mjbvz/vscode-markdown-mermaid#44]
Azure Data Studio is built on VS Code and is mostly compatible. It lets you edit markdown in the same way, and also allows markdown code blocks in Jupyter style notebooks. It uses the same VSIX format for extensions also.

I tried installing the VSIX in it manually and my observation is that neither of those two scenarios work right now which isn't unexpected ^^ 

Specifically the md files do recognise the ``` mermaid block comes out in the preview as a grey block (so it seemingly passes it onto the extension but something goes wrong - if you changed it to mermaid2 or something else nonsensical then it renders as a normal dummy code block). The Jupyter style notebooks though are always rendering as normal text so probably don't get passed on (but if they did that would have been cool...).

I don't know enough to create or edit these extensions (maybe one day) but I wanted to put it up here as a feature request in case others show interest because this extension is unequalled and I use it a lot.

**Comment by mjbvz** [comment]
Can you share an code example where this extension doesn't work

**Comment by mjbvz** [comment]
Closing this as not actionable without additional info
