### ISSUE TITLE
Inline style not working .

### ISSUE THREAD

**Issue by 625781186** [mjbvz/vscode-markdown-mermaid#45]
```
Start((<img src='https://iconscout.com/ms-icon-310x310.png' width='20' height='20' /> 开始))
           --> node_types{node_types?}
```

![image](https://user-images.githubusercontent.com/30521429/71477073-028d4300-2823-11ea-9697-9f5e910d2c8d.png)

Typora :
![image](https://user-images.githubusercontent.com/30521429/71477105-2b153d00-2823-11ea-9856-9c5fe8dfbad2.png)

**Comment by mjbvz** [comment]
Please provide  steps to reproduce the problem

**Comment by 625781186** [comment]
> Please provide steps to reproduce the problem

1. create .md file ;

2. cope this txt to .md file  :
```
    
​```mermaid

graph TB
%%subgraph one 
	开始((<img src='https://iconscout.com/ms-icon-310x310.png' width='20' height='20' /> 开始))
	--> node_types{node_types?}
	
node_types 
	-->|=FireBox<br>辐射段|辐射段[<a href='https://www.google.com'>JF.call_from_py_add_node_FireBox</a>]
	
	node_types 
	-->|=ConvectionSection<br>对流段|对流段[JF.callfrom_py_add_node_ConvectionSection]
	
	node_types 
	-->|=<br>管束或炉管|管束或炉管[JF.call_from_py_add]
	
	辐射段   --> node_mixin.js
	对流段   --> node_mixin.js
	管束或炉管--> node_mixin.js
	
	node_mixin.js
	-->add_node[根据不同的节点类型, 调用不同的模板]
	-->Template[Template 和 AttrTemplate]
	%%
	Template -->|key=uuid| call_back
	Template --> 选中触发[<a href='#1.1 选中节点触发'>选中触发</a>] 
​```
```

3. I hope get resule:
    
![image](https://user-images.githubusercontent.com/30521429/71572497-61e89d00-2b1a-11ea-8dc1-26c5df1fe255.png)


4. but  Inline style not working :

![image](https://user-images.githubusercontent.com/30521429/71572514-7f1d6b80-2b1a-11ea-9fa7-b51f51764768.png)

**Comment by mjbvz** [comment]
That example code does not work for me in VS Code or on the mermaid website:


<img width="1810" alt="Screen Shot 2020-09-03 at 2 11 17 PM" src="https://user-images.githubusercontent.com/12821956/92167959-64a93980-edef-11ea-8928-ec41a5652621.png">


Please share an updated, minimal graph that demonstrates the problem

**Comment by mjbvz** [comment]
Closing as we need simple steps to reproduce this issue
