### ISSUE TITLE
Syntax error detection

### ISSUE THREAD

**Issue by frankshearar** [mjbvz/vscode-markdown-mermaid#46]
Right now if I make a grammatically incorrect line, I get no rendered diagram at all. If I'm editing several dozen lines of sequence diagrams it would be super helpful to have some way of detecting that I have dropped a : or whatever.

Whether that's through syntax highlighting or "best effort" rendering (rendering everything up to the error), I don't mind, as long as I have _a_ way of detecting how I've messed up.

**Comment by mjbvz** [comment]
This sounds like an issue or limitation with the mermaid library itself

Please file an issue upstream to see if they can produce better syntax errors or fallback to best effort rendering
