### ISSUE TITLE
Visual "cursor" when editing

### ISSUE THREAD

**Issue by frankshearar** [mjbvz/vscode-markdown-mermaid#48]
I'm currently editing a fairly complicated sequence diagram. I keep losing my place - while I can always see, obviously, where my text cursor is, I have to spend time trying to find the visual location corresponding to the cursor position, in the sequence diagram.

This would be useful in graphs and digraphs, too, where the renderer could highlight the node I'm currently editing.

**Comment by mjbvz** [comment]
Closing since there haven't been upvotes on this issue for almost a year 

This seems like a better fit for a dedicated mermaid editor
