### ISSUE TITLE
Generated images are clipping text

### ISSUE THREAD

**Issue by duncanawoods** [mjbvz/vscode-markdown-mermaid#49]
All my images are clipping text on Ubuntu 18.04 e.g.

``` 
graph TB
  A(This is a string) --> B(This is another string)
```
![vscode mermaid cut-off](https://user-images.githubusercontent.com/2480457/72217438-8a629500-3525-11ea-88b2-719f47025e20.png)

Extra info:

- Happens with no other extensions enabled
- Happens on Linux but not on on Windows
- Happens on multiple Linux machines
- Happens on all past versions over the last year
- Happens even if I rebuild with latest dependencies & Mermaid 8.4.4
- Doesn't happen with github rendering or online mermaid tool
- Doesn't happen with mermaid-cli on the same Ubuntu machines

I guess it's something Linux specific in the VS Code rendering but I'd appreciate ideas of a work-around.

Version details:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic
```

```
Name: Markdown Preview Mermaid Support
Id: bierner.markdown-mermaid
Description: Adds Mermaid diagram and flowchart support to VS Code's builtin markdown preview
Version: 1.4.1
Publisher: Matt Bierner
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? It includes a new electron version

**Comment by duncanawoods** [comment]
Thanks, that's helped narrow it down. It's related to the user-interface zoom-level at the time the image is generated. This is controlled with `window.zoomlevel` in settings.json and the `ctrl-/ctrl+` keyboard shortcuts.

Once you have generated an image, changing the zoom level won't fix it, just make it bigger/smaller, so it's not the stylesheet of the markdown preview but some style information from the current user-interface state that is affecting the image generation in an undesirable way.

If you zoom-out like me (at -1) then you get clipping. Alternatively, if you zoom-in and generate images you then get excess padding e.g. zoom level 3 look like this:

![Screenshot from 2020-01-13 22-07-08](https://user-images.githubusercontent.com/2480457/72296242-102f2f00-3651-11ea-8df0-fc9589b9f672.png)

**Comment by aidandj** [comment]
Same problem here. When I have `window.zoomlevel` set to anything below 0, I also get the clipped images.

**Comment by tjohnsonhvac** [comment]
I am having the same issue at zoom level 0 ( I assume, I made sure to go to settings and select 'Reset Zoom')

Zooming in and out changes how much is clipped but I cant get it to display the entire text at any zoom level.

VScode Version:
```
Version: 1.44.0-insider (user setup)
Commit: 0dbae2083aff6ff2190c8e2157be95458915d464
Date: 2020-04-03T05:44:09.945Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

```
graph TD;

A("ModbusMaster.read()") 
B("ModbusBaseConnection.read()<br/>Create ModbusPollItem<br/>add it to [m_priority_queue]")
C[/"m_priority_queue<br/>ModbusPollItem*"\]
D("ModbusBaseConnection::poll_task()<br/>remove from[m_priority_queue]<br/>ModbusBasConnection.modbus_library_read()")

%% Connections
A--> B
B--> C
C--> D
C--> B
D--> C
```
VScode:
![image](https://user-images.githubusercontent.com/36667609/78451042-ed5d5700-7650-11ea-99a3-5c883992ffda.png)

Mermaid.js Live Editor:
![image](https://user-images.githubusercontent.com/36667609/78451046-fbab7300-7650-11ea-962a-2c0911157cf4.png)

**Comment by mjbvz** [comment]
These examples doesn't render for me at in the latest release. Can you please share an updated example

**Comment by duncanawoods** [comment]
I don't understand. The first example is the simplest possible bit of mermaid.

It renders and and still clips with zoom -1 in version 1.9.0.

    ``` mermaid
    graph TB 
      A(This is a string) --> B(This is another string)
    ```

**Comment by duncanawoods** [comment]
@mjbvz can you give a pointer to where the mermaid invocation happens in the code please? I tried to help out but can't find it!

**Comment by mjbvz** [comment]
This also happens in the mermaid live editor for me: [svg example](https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVEJcbiAgQShUaGlzIGlzIGEgc3RyaW5nKSAtLT4gQihUaGlzIGlzIGFub3RoZXIgc3RyaW5nKVxuICAiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsInRoZW1lVmFyaWFibGVzIjp7ImJhY2tncm91bmQiOiJ3aGl0ZSIsInByaW1hcnlDb2xvciI6IiNFQ0VDRkYiLCJzZWNvbmRhcnlDb2xvciI6IiNmZmZmZGUiLCJ0ZXJ0aWFyeUNvbG9yIjoiaHNsKDgwLCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5Qm9yZGVyQ29sb3IiOiJoc2woMjQwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInNlY29uZGFyeUJvcmRlckNvbG9yIjoiaHNsKDYwLCA2MCUsIDgzLjUyOTQxMTc2NDclKSIsInRlcnRpYXJ5Qm9yZGVyQ29sb3IiOiJoc2woODAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeVRleHRDb2xvciI6IiMxMzEzMDAiLCJzZWNvbmRhcnlUZXh0Q29sb3IiOiIjMDAwMDIxIiwidGVydGlhcnlUZXh0Q29sb3IiOiJyZ2IoOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSkiLCJsaW5lQ29sb3IiOiIjMzMzMzMzIiwidGV4dENvbG9yIjoiIzMzMyIsIm1haW5Ca2ciOiIjRUNFQ0ZGIiwic2Vjb25kQmtnIjoiI2ZmZmZkZSIsImJvcmRlcjEiOiIjOTM3MERCIiwiYm9yZGVyMiI6IiNhYWFhMzMiLCJhcnJvd2hlYWRDb2xvciI6IiMzMzMzMzMiLCJmb250RmFtaWx5IjoiXCJ0cmVidWNoZXQgbXNcIiwgdmVyZGFuYSwgYXJpYWwiLCJmb250U2l6ZSI6IjE2cHgiLCJsYWJlbEJhY2tncm91bmQiOiIjZThlOGU4Iiwibm9kZUJrZyI6IiNFQ0VDRkYiLCJub2RlQm9yZGVyIjoiIzkzNzBEQiIsImNsdXN0ZXJCa2ciOiIjZmZmZmRlIiwiY2x1c3RlckJvcmRlciI6IiNhYWFhMzMiLCJkZWZhdWx0TGlua0NvbG9yIjoiIzMzMzMzMyIsInRpdGxlQ29sb3IiOiIjMzMzIiwiZWRnZUxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJhY3RvckJvcmRlciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImFjdG9yQmtnIjoiI0VDRUNGRiIsImFjdG9yVGV4dENvbG9yIjoiYmxhY2siLCJhY3RvckxpbmVDb2xvciI6ImdyZXkiLCJzaWduYWxDb2xvciI6IiMzMzMiLCJzaWduYWxUZXh0Q29sb3IiOiIjMzMzIiwibGFiZWxCb3hCa2dDb2xvciI6IiNFQ0VDRkYiLCJsYWJlbEJveEJvcmRlckNvbG9yIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwibGFiZWxUZXh0Q29sb3IiOiJibGFjayIsImxvb3BUZXh0Q29sb3IiOiJibGFjayIsIm5vdGVCb3JkZXJDb2xvciI6IiNhYWFhMzMiLCJub3RlQmtnQ29sb3IiOiIjZmZmNWFkIiwibm90ZVRleHRDb2xvciI6ImJsYWNrIiwiYWN0aXZhdGlvbkJvcmRlckNvbG9yIjoiIzY2NiIsImFjdGl2YXRpb25Ca2dDb2xvciI6IiNmNGY0ZjQiLCJzZXF1ZW5jZU51bWJlckNvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IiOiJyZ2JhKDEwMiwgMTAyLCAyNTUsIDAuNDkpIiwiYWx0U2VjdGlvbkJrZ0NvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IyIjoiI2ZmZjQwMCIsInRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJ0YXNrQmtnQ29sb3IiOiIjOGE5MGRkIiwidGFza1RleHRMaWdodENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dERhcmtDb2xvciI6ImJsYWNrIiwidGFza1RleHRPdXRzaWRlQ29sb3IiOiJibGFjayIsInRhc2tUZXh0Q2xpY2thYmxlQ29sb3IiOiIjMDAzMTYzIiwiYWN0aXZlVGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsImFjdGl2ZVRhc2tCa2dDb2xvciI6IiNiZmM3ZmYiLCJncmlkQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JrZ0NvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCb3JkZXJDb2xvciI6ImdyZXkiLCJjcml0Qm9yZGVyQ29sb3IiOiIjZmY4ODg4IiwiY3JpdEJrZ0NvbG9yIjoicmVkIiwidG9kYXlMaW5lQ29sb3IiOiJyZWQiLCJsYWJlbENvbG9yIjoiYmxhY2siLCJlcnJvckJrZ0NvbG9yIjoiIzU1MjIyMiIsImVycm9yVGV4dENvbG9yIjoiIzU1MjIyMiIsImNsYXNzVGV4dCI6IiMxMzEzMDAiLCJmaWxsVHlwZTAiOiIjRUNFQ0ZGIiwiZmlsbFR5cGUxIjoiI2ZmZmZkZSIsImZpbGxUeXBlMiI6ImhzbCgzMDQsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlMyI6ImhzbCgxMjQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNCI6ImhzbCgxNzYsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlNSI6ImhzbCgtNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU2IjoiaHNsKDgsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlNyI6ImhzbCgxODgsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSJ9fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

<img width="199" alt="Screen Shot 2020-11-20 at 1 39 37 PM" src="https://user-images.githubusercontent.com/12821956/99852440-d878f980-2b35-11eb-8e7f-e0bd91f92c8e.png">

Please start by filing this issue against Mermaid itself
