### ISSUE TITLE
Flowchart Database does not render image

### ISSUE THREAD

**Issue by heliomcp** [mjbvz/vscode-markdown-mermaid#50]
Does not render the cilinder for the database

`id11[(DataBase)]`

**Comment by mjbvz** [comment]
Does this repo in the mermaid cli?

**Comment by heliomcp** [comment]
I am trying it from this documentation https://mermaid-js.github.io/mermaid/#/flowchart?id=a-node-in-a-cylindrical-shape

**Comment by mjbvz** [comment]
What mermaid version did you try it with?

**Comment by heliomcp** [comment]
I am only using mermaid in the Visual Studio Code with this addon:

![image](https://user-images.githubusercontent.com/9692595/73058025-a7368b00-3e8a-11ea-84c2-5d014440e3e1.png)

**Comment by jonlm** [comment]
I'm having the same problem. Same versions of everything. Also, the "multiple nodes in links" syntax fails as well. For example:

graph LR
   a --> b & c--> d

Which works in the mermaid live editor:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgIGEgLS0-IGIgJiBjLS0-IGQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgIGEgLS0-IGIgJiBjLS0-IGQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by jonlm** [comment]
Starting to think that both of these features are simply newer than the original 8.4 that's in the vscode plugin. For example the database node was added in 8.4.5, released 18 days ago: https://github.com/mermaid-js/mermaid/releases/tag/untagged-f43366252632a1a42020

**Comment by enbandari** [comment]
I made a pull request to upgrade mermaid to 8.4.6. 

As a workaround, you can download the file from my forked [page.bundle.js](https://github.com/enbandari/vscode-markdown-mermaid/raw/master/page.bundle.js) and override the installed directly here in the extensions folder:

$VSCODE_EXTENSIONS_FOLDER/bierner.markdown-mermaid-1.4.1/page.bundle.js.

While the VSCODE_EXTENSIONS_FOLDER is according to your os:

* Windows %USERPROFILE%\.vscode\extensions
* Mac $HOME/.vscode/extensions
* Linux $HOME/.vscode/extensions

**Comment by mjbvz** [comment]
Fixed by  #51
