### ISSUE TITLE
Support for exporting mermaid files .mmd to svg images

### ISSUE THREAD

**Issue by damnlogin** [mjbvz/vscode-markdown-mermaid#54]
Hello - it would be very nice to have ability to export mermaid files to svg images with some command or probably automatically on valid markup save.

**Comment by samuelchen** [comment]
+1
But not limited to .mmd.
Better add a **button** or **menu item** to export the live preview as SVG/PNG/PDF/...

**Comment by mjbvz** [comment]
Doesn't this mermaid cli do this?

**Comment by damnlogin** [comment]
> Doesn't this mermaid cli do this?

I believe it does but it would be just perfect having mmd file selected to type `Ctrl` + `Shift` + `P` in VSCode and type a command like Mermaid: Export to SVG

**Comment by mjbvz** [comment]
This seems like a better fit for a mermaid extension like: https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview

**Comment by damnlogin** [comment]
Agree. Closing this one then. As a workaround for anyone interested for now I use the following VSCode task:

```json
{
  "version": "2.0.0",
  "windows": {
        "options": {
            "shell": {
                "executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "args": [
                    "-NoProfile",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-Command"
                ]
            }
        }
  },
  "tasks": [
    {
      "label": "Mermaid: Export to Svg",
      "type": "shell",
      "command": "if ($([io.path]::GetExtension('${file}')) -eq '.mmd') { mmdc -i '${file}' -o $([io.path]::ChangeExtension('${file}', 'svg')) }",
      "presentation": {
        "reveal": "never"
      },
      "problemMatcher": []
    }
  ]
}
```
