### ISSUE TITLE
Support mermaid 8.5

### ISSUE THREAD

**Issue by emmkong** [mjbvz/vscode-markdown-mermaid#58]
With version 8.5 there are some bug fixes and enhancements, plus a new diagram type, entity-relationship diagrams.

https://github.com/mermaid-js/mermaid/releases/tag/untagged-31c93788afe260d914bb

**Comment by ontoneio** [comment]
Realizing some of the documentation from Mermaid and the Plugin here for VsCode are not matching up.

As an example in `flowchart` types

```
flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
```
The above works, and below does not.

```
flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
    one --> two
    three --> two
    two --> c2
```

Hope that helps a bit.
An upgrade to the latest version would be helpful.

**Comment by italomaia-bk** [comment]
Mermaid support was upgraded to 8.5.1

**Comment by emmkong** [comment]
@italomaia cool. Thanks.
