### ISSUE TITLE
user journey diagram seems to not be working

### ISSUE THREAD

**Issue by italomaia** [mjbvz/vscode-markdown-mermaid#63]
Tried to render the example user journay for mermaid without success:
```mermaid
journey
    title My working day
    section Go to work
        Make tea: 5: Me
        Go upstairs: 3: Me
        Do work: 1: Me, Cat
    section Go home
        Go downstairs: 5: Me
        Sit down: 5: Me
```
It renders as a black empty square.

**Comment by italomaia** [comment]
Maybe update the mermaid package version?

**Comment by GiovanniCardamone** [comment]
you can try to fork and update mermaid version i package.json

**Comment by italomaia** [comment]
I can do it, but how do I test it?

**Comment by GiovanniCardamone** [comment]
you can install extension locally on vscode 
https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually

**Comment by italomaia** [comment]
Ok; how do I update the page bundle?

**Comment by italomaia** [comment]
@GiovanniCardamone ta dah: https://github.com/mjbvz/vscode-markdown-mermaid/pull/64
Weird thing is that the generated license file does not match the current one, so I skipped it.

**Comment by GiovanniCardamone** [comment]
you should close this issue and open new one i think
