### ISSUE TITLE
Doesn't work in collapsible sections

### ISSUE THREAD

**Issue by user-name-is-taken** [mjbvz/vscode-markdown-mermaid#68]
For example, the following won't work.

~~~markdown
<details><summary><u><b>Table of contents</b></u></summary>

```mermaid
graph LR
    fa:fa-check-->fa:fa-coffee
```

</details>
~~~

[Collapsible sections reference](https://stackoverflow.com/questions/31562552/collapsible-header-in-markdown-to-html)

**Comment by mjbvz** [comment]
Seems to work fine in the latest release. Also see #102
