### ISSUE TITLE
Publish extension to Open VSX

### ISSUE THREAD

**Issue by John3** [mjbvz/vscode-markdown-mermaid#69]
Hey can you make available this extension to [Open VSX](https://github.com/eclipse/openvsx) marketplace? and have it available for [VSCodium](https://vscodium.com/).

> Open VSX is a [vendor-neutral](https://projects.eclipse.org/projects/ecd.openvsx) open-source alternative to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/vscode). It provides a server application that manages [VS Code extensions](https://code.visualstudio.com/api) in a database, a web application similar to the VS Code Marketplace, and a command-line tool for publishing extensions similar to [vsce](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce).

There is a guide over here to publish it: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by mjbvz** [comment]
I only test this extension in VS Code and will not able to test/support other editors properly (even if they theoretically should be able to run the extension)

**Comment by jooola** [comment]
@mjbvz This is sad. Any chances that this can be reconsidered ?

I am using VSCodium, and it doesn't diverge from vscode, so it should not bother you with an extra editor to support.
And if any other IDE has some issue this maybe (take it with a grain of salt) means the vsx api isn't fully met. So not your shoulders.

**Comment by John3** [comment]
I think you should not worry to test/support other editors 😉 

Based on the license, anyone can publish the extension preserving the copyright and license, so, I think the issue can keep open with a label until someone take the time to publish to OpenVSX if there is enough interest.
