### ISSUE TITLE
Unable to install from market place

### ISSUE THREAD

**Issue by djczaski** [mjbvz/vscode-markdown-mermaid#7]
I click the green `Install` button which turns blue and says `Installing`. After a minute, the button turns back green and says `Install`.

I tried mermaid in markdown, but it does not render. 

I'm on macOS Sierra (10.12.5) and Code version 1.15.1.

**Comment by mjbvz** [comment]
Can you install other extensions?

**Comment by djczaski** [comment]
I just added emojisense and that worked fine.

**Comment by mjbvz** [comment]
Can you please try installing again and if the install fails, open the developer tools window using the `Developer: Toggle developer tools` command in VS Code. Are there any error messages in the developer console?

**Comment by djczaski** [comment]
It finally installed, although I have no idea how it happened and I can't get it to break again.

I did have another Mermaid preview installed which I removed.

**Comment by mjbvz** [comment]
Glad you were able to install. Closing since i'm not sure the issue was related to this extension specifically
