### ISSUE TITLE
[QUESTION] Where are the data "processed"?

### ISSUE THREAD

**Issue by arnaduga** [mjbvz/vscode-markdown-mermaid#78]
Hello

Thanks for the job's done on this extension, I like to use Mermaid in my docs!

I'm working now in a company which is really worried about data and information security. I'm wondering where is processed the data?

I don't know if you are using the `mermaid.min.js` file locally (somewhere in extension folder) or somewhere remotely.

Can you help me?

Thanks

**Comment by mjbvz** [comment]
It's done locally by the mermaid library
