### ISSUE TITLE
No default styles applied to diagrams - fresh install - black diagrams

### ISSUE THREAD

**Issue by logularjason** [mjbvz/vscode-markdown-mermaid#79]
Hello,

The diagrams appear black as shown in the screenshot after installation of the extension via the VS extension UI.  

I've played around with markdown.styles with no joy by trying different scss file locations - also shown in the screenshot.

Q: Is this a bug?  If not, how to set up the default styles?  Is this documented?

Thanks for the extension!!

![image](https://user-images.githubusercontent.com/53684229/91648924-1cb5aa00-eab1-11ea-8146-6f590f6daea0.png)

**Comment by logularjason** [comment]
VS code is up to date

Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
This looks expected. If you are using a dark theme in VS Code, we use mermaid's dark theme. 

For guidance on styling mermaid, see the mermaid docs
