### ISSUE TITLE
Can't find package in marketplace.

### ISSUE THREAD

**Issue by lorenzofollador** [mjbvz/vscode-markdown-mermaid#88]
The package is not available for download in marketplace (location: Brazil)
![image](https://user-images.githubusercontent.com/22060570/99189144-8a7f8280-273e-11eb-8ff6-ade3df806150.png)
Photo for reference.

**Comment by mjbvz** [comment]
This is not an issue with this extension. Please file the issue related to marketplace search against VS Code itself
