### ISSUE TITLE
Support for Jekyll-Tags; additional to code fences

### ISSUE THREAD

**Issue by N7K4** [mjbvz/vscode-markdown-mermaid#91]
I am using a markdown based blog with [jekyll](https://jekyllrb.com/). Jekyll do have a support for tags, tags are block like `{% mytag %}` or `{%- mytag -%}` to trim whitespaces. The tags are woking fine when jekyll generates the html, but not in the preview inside vscode, where it is not recocgnized by the add-in as code.

Would it be possible that this VScode extension can handle **jekyll-tag-syntax** as well?

```markdown
{%- mermaid -%}
graph LR
    A-->B
    B-->C
    C-->D
{%- endmermaid -%}
```

Code fences ` ``` ` and ` ::: ` works great for preview.

**Comment by mjbvz** [comment]
Closing as there hasn't been any further interest expressed in this issue since it was opened last December
