### ISSUE TITLE
HTML support for node text

### ISSUE THREAD

**Issue by jmutchek-msft** [mjbvz/vscode-markdown-mermaid#96]
I have seen several references online to people inserting html into node text (though I can't find anything in the mermaid docs about it) and it seems to work in the [Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBpZDEoU3RhcnQpLS0-aWQyKE1pZClcbiAgICBpZDItLT5pZDMoPHN0cm9uZz5FbmQ8L3N0cm9uZz4pIiwibWVybWFpZCI6eyJzZWN1cml0eUxldmVsIjoiYW50aXNjcmlwdCIsImZsb3djaGFydCI6eyJodG1sTGFiZWxzIjp0cnVlfX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9). I haven't been able to get it to work with this previewer, however. For example,

```mermaid
:::mermaid
%%{init: { 'securityLevel': 'antiscript', 'flowchart': { 'htmlLabels':true } } }%%
graph LR
    id1(Start)-->id2(Mid)
    id2-->id3(<strong>End</strong>)
:::
```

![image](https://user-images.githubusercontent.com/19610772/106906838-93dc1380-66cb-11eb-9b81-8f3aa32ea3fc.png)

Is the previewer enforcing a strict security level perhaps? Should this be possible and I just have the config wrong? Thanks.

**Comment by Pindar777** [comment]
@jmutchek-msft Does the `%%{init...` has an effect on the output?
How do you compile the code?
I'm using markdown-all-in-one and cannot pass any config parameters...

**Comment by mjbvz** [comment]
This works for me in the most recent version (change to use underline instead of `strong` to make this more obvious):

![Screen Shot 2022-05-17 at 11 54 05 AM](https://user-images.githubusercontent.com/12821956/168888981-fec506b7-40ea-454c-a21e-85854a606fa2.png)
