### ISSUE TITLE
VS Codium Support

### ISSUE THREAD

**Issue by bevsxyz** [mjbvz/vscode-markdown-mermaid#99]
Hi,
Could you push the extension to https://open-vsx.org/ which serves extensions for VS Codium, the publishing process is documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). I use VS Codium for it's opensourse licence and not having any backlinks to microsoft.

**Comment by mjbvz** [comment]
Closing as this would create extra work to both publish and maintain

**Comment by bevsxyz** [comment]
It's alright. But there was a documented GitHub actions you know, which would be easier to deploy.

https://github.com/HaaLeo/publish-vscode-extension#readme
